### ISSUE TITLE
Zigbee Geräte werden erkannt aber nicht übernommen

### ISSUE THREAD

**Issue by Matten-Matten** [hobbyquaker/node-red-contrib-zigbee#101]
Hallo @hobbyquaker,
Ich wollte gestern mein raspberrymatic system inklusive Node-RED von einem Tinkerboard zu einem Rpi4 übertragen. 
Ich hab ein vollständiges Backup gemacht (mit dem kompletten redmatic) und habe das erfolgreich auf dem Rpi4 restoren können. Nach dem Neustart konnte ich alle zigbee Aktoren schalten. Als ich die zentrale erneut heruntergefahren hab um im Router die IP-Adresse der zentrale zu wechseln (um die gleiche IP-Adresse vom altsystem zu bekommen) und die zentrale neu startete. Waren alle zigbee Aktoren nicht mehr in der Angelernten Liste 😒.

Also wie schon so oft hab ich alle Aktoren erneut angelernt. Ich besitze 6 Osram Plugs der alten Generation, die sich wunderbar anlernen lassen und 4 der neueren Generation (Plug Z3). 2 der neuen Generation konnte ich erfolgreich in die Liste aufnehmen. Aber die anderen zwei hat der stick erkannt und auch den Typ usw. Übermittelt bekommen aber die beiden blieben grau hinterlegt und "schoben" sich in der device Liste nicht nach oben. Auch eine lange Zeit warten brachte kein Erfolg. OK beide Aktoren noch einmal abgelernt. Den z Stack abgezogen Node Red gestartet und erneut versucht, ohne Erfolg wieder das selbe. Nun war es gestern schon spät geworden, also die beiden Problem Kinder wieder abgelernt und Node Red neu gestartet und wieder sind alle Aktoren aus der device Liste verschwunden 🤯🤯🤯🤯!
Ich hätte warnsinnig werden können gestern. 

Meine Frage ist wie ich die letzten beiden Plugs von Grau hinterlegt in die erfolgreich erkannt Ebene bekomme. Hast du eine Idee warum das so Auftritt?

Gruß
Matten Matten

**Comment by Matten-Matten** [comment]
Mitlerweile, hab ich alle aktoren anlernen können, aber einmal nodered gestartet und mal wieder alles mühsehlig angelernte ist verschwunden. ......

**Comment by Hypnos3** [comment]
Ich würde an Deiner Stelle komplett Sauber beginnen:
 - Herdsman Config löschen + Deploy
 - Node Red stoppen
- Stick abziehen

Sämtliche Ordner mit dev.db und deren Backup löschen. Geht nur über SSH, den Pfad findest du im Redmatic Log

Optional: Den Stick vor dem neuen Einstecken auch neu flashen schadet nicht. Irgendwie merken sich NR, Herdsmen und der Stick ihre configs an gefühlt 37 Stellen. Hab das auch schon ein paarmal durch und bin noch nicht so ganz dahinter gestiegen. Das Anlernen der Geräte ist halt extremst lästig vor allem wenn fest verbaut.

Stick stecken

NR starten

Neuen Herdsman mit neuem Network-Key und neuer panID anlegen

**Comment by Matten-Matten** [comment]
OK, das werde ich alles Testen. Merkwürdig ist auch immer wieder das die device Liste immer wieder leer ist. Nach einem Neustart oder ähnliches.

**Comment by Matten-Matten** [comment]
Mir ist auch aufgefallen das redmatic ständig stoppt. Ich versuche ein Backup der ccu zu machen, werde die flows sichern und redmatic komplett deinstallieren. Und neu installieren, dann alles wieder neu und frisch drauf. Auch die nodes. Dann Mal schauen ob das fruchtet. Denn irgendwie macht das alles Probleme. Node Red stoppt wenn ich Alexa anspreche und auch nur bei bestimmten smarthome befehlen. Hab aus dem Log noch nicht die Ursache lesen können. Vermutlich irgendwelche cuxd Geräte die Node Red nicht mag. Vielleicht liegt es auch an der Raspberrymatic Version, denn auf meinem altsystem läuft eine Versionen vom September 2019 und ich hab auf dem neuen System die aktuelle Version laufen. Vielleicht hat sich auch da was verändert. Oder das node-red-contrib-ccu Node....

Hab mir das mit dem Systemwechsel deutlich problemloser vorgestellt...

**Comment by Matten-Matten** [comment]
was bedeutet eigentlich folgende Log Meldung?

`Jan 30 15:20:58 ccu3-webui daemon.err node-red: (node:1169) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

**Comment by Matten-Matten** [comment]
@Hypnos3 
du hast geschrieben:

> Damit läuft bei mir alles gut. Ich hatte nur Probleme mit dem Zigbee Stack 3. Damit wurde der CC2531 nach jedem Neustart nicht mehr erkannt und die Reichweite war nicht gut. Bin danach auf den 2er Stack mit Routing und ich muss sagen das mein Zigbee Netzwerk noch nie so gut funktionierte (hatte vorher den 2er Stack ohne Routing).

Was meinst du damit? wie ist das aufgebaut bzw wie kann man das einstellen ?

Bei meinem erkannten CC2531 Stick steht " zStack12 / 2.6.3 20190608".

Gruß
Matten Matten

**Comment by Hypnos3** [comment]
Als ZStack wird die Firmware des Zigbee Sticks genannt und du hast die aktuellste Version. Davon gibt es aber 2 verschiedene. Die normale und eine mit "source routing". Wenn ich das richtig verstehe, können bei der source Routing Version weniger Geräte direkt Coordinator gesteuert werden, dafür merkt sich der Coordinator die Route zu einem Gerät über die Router. 
Die Firmwares für die Coordination oder Router findet man hier:
https://github.com/Koenkk/Z-Stack-firmware/tree/master

Die Pan ID ist die eindeutige Bezeichnung des Netzwerkes. Sollte nur Bedeutung haben wenn es mehrere Zigbee Netzwerke in der Nachbarschaft gibt. (Ich habe da auch keine Ahnung und das jetzt auch nur gegoogelt.)

**Comment by Matten-Matten** [comment]
ok vielen Dank!

**Comment by spiu16** [comment]
Ich habe das gleiche Problem. Meine Devices-Liste ist ebenfalls ständig wieder leer, nachdem ich Node-RED neu starte.
Habe auch schon den RaspPi ausgewechselt, daran lag's also nicht. Meine aktuelle Firmware vom CC2531 ist noch 2.6.3 20190223. 
Bis vor ein paar Wochen lief das alles problemlos, und dann plötzlich "vergisst" er regelmäßig die Devices.
Würde es helfen wenn ich das Debug-Log von Redmatic bereitstelle?
Danke und Grüße!

**Comment by Matten-Matten** [comment]
Trotz der Anleitung von @Hypnos3  sind gestern wieder alle Geräte verschwunden.
Ich weiß auch nicht weiter.
