### ISSUE TITLE
Command form one device to another

### ISSUE THREAD

**Issue by lainbh** [hobbyquaker/node-red-contrib-zigbee#102]
Hello.
I have 2 device: Xiaomi Switch (https://www.zigbee2mqtt.io/devices/WXKG01LM.html) and Xiaomi Wall Switch (https://www.zigbee2mqtt.io/devices/QBKG04LM.html) for lamp.

With dashboard Switch node I can control Wall Switch (with msg.cmd and Command node).
But with Xiaomi Switch can't control Wall Switch. Flow:
Converter node (Xiaomi Switch) - Switch node ("single" state for single click event to first output) - Change node (msg.cmd to "off") - Command node (ieeeAddr - Xiaomi Wall Switch, endpoint 2, cluster genOnOff).
With single click at Command node was error "Endpoint for Xiaomi Switch not found".
Why in Command node used ieeeaddr form Converter node and not used which choose in this node?

**Comment by Sineos** [comment]
The message properties from your input  (Xiaomi Switch) most likely override the settings from your Xiaomi Wall Switch Command node.

Try importing following node and place it before the Command node:
```
[{"id":"eaf72a4c.7a8748","type":"function","z":"10976a86.e81645","name":"Clean msg Object","func":"msg = {};\nmsg.payload = true;\nreturn msg;","outputs":1,"noerr":0,"x":830,"y":220,"wires":[["7fb7a79.a2444d8"]]}]
```

**Comment by lainbh** [comment]
Thank you. It's work.

**Comment by Sineos** [comment]
Great. Please close this issue.
