### ISSUE TITLE
Basic question: how start a command node (execute) 

### ISSUE THREAD

**Issue by get-command** [hobbyquaker/node-red-contrib-zigbee#113]
Hallo Community, Hallo @hobbyquaker,

hier kann ich ja in Deutsch schreiben, habe ich gerade gesehen :-)

Meine Frage ist vermutlich ganz einfach, aber für mich bisher nicht zu lösen gewesen.

![grafik](https://user-images.githubusercontent.com/67456251/85916249-215ea780-b84f-11ea-84b6-b94c4e48e977.png)

Wie in der Grafik zu sehen ist, kann ich die Command-Nodes starten, wenn ich direkt die Injects ausführe. Das ist ein Zeichen dafür, dass der Command-Node richtig mit der ZigBee-Lampe (Osram) konfiguriert ist. Wenn ich aber einen Switch habe, funktioniert das nicht mit diesem Gerät. Hänge ich statt dem ZigBee-Gerät ein andere Gerät an, funktioniert das auch problemlos. Das ist ein Zeichen dafür, dass der Switch-Node funktioniert. Muss ich, nachdem Switch-Node noch einen Zwischen-Node einbinden, der den Command-Node sagt "Jetzt für den Befehl aus"? Ich habe wirklich extrem viel getestet und sehr viel im Internet recherchiert.  Über einen Tipp wäre ich sehr glücklich.

Vielen Dank für die Hilfe.

**Comment by Sineos** [comment]
Bitte mal eine Debug Node an den Switch hängen (complete message object) und zeigen was die Switch-Node ausgibt

**Comment by get-command** [comment]
> Bitte mal eine Debug Node an den Switch hängen (complete message object) und zeigen was die Switch-Node ausgibt

Der Switch-Node gibt, abhängig vom Smartbutton-Klick (doppelt oder einfach), entweder OnOff: 0 oder OnOff:2  weiter.

**Comment by Sineos** [comment]
Ohne Debug Message bin ich raus

**Comment by get-command** [comment]
> 
> 
> Ohne Debug Message bin ich raus

meinst das?!

![grafik](https://user-images.githubusercontent.com/67456251/85917795-9933ce80-b85d-11ea-96df-caf8b92454a6.png)

**Comment by Sineos** [comment]
Bitte die Debug Node auf "complete Message object" setzen und ausklappen. Das Schwärzen kannst die sparen, du postest ja nicht deinen Netzwerkschlüssel

**Comment by get-command** [comment]
> 
> 
> Bitte die Debug Node auf "complete Message object" setzen und ausklappen. Das Schwärzen kannst dir sparen, du postest ja nicht deinen Netzwerkschlüssel

hab dein eingestellt im debug node:

![grafik](https://user-images.githubusercontent.com/67456251/85918163-8c64aa00-b860-11ea-952d-55741026e2fd.png)

dann steht da tatsächlich mehr:

![grafik](https://user-images.githubusercontent.com/67456251/85918213-f5e4b880-b860-11ea-964c-3bc7ef66afb9.png)

**Comment by Sineos** [comment]
Setze mal zwischen "Smart Button" und Switch-Node eine Function-Node mit folgendem Inhalt:
```
msg = {};
msg.payload = true;
return msg;
```

**Comment by get-command** [comment]
Funktioniert leider nicht

![grafik](https://user-images.githubusercontent.com/67456251/85918583-72c56180-b864-11ea-87ba-de8b4b8bff9a.png)

**Comment by stuckis6er** [comment]
Hallo,
wie sieht denn der Switch aus? Es wundert mich das ein payload mit onOff 0  bei der Licht an Node ankommt.

**Comment by get-command** [comment]
> 
> 
> Hallo,
> wie sieht denn der Switch aus? Es wundert mich das ein payload mit onOff 0 bei der Licht an Node ankommt.

![grafik](https://user-images.githubusercontent.com/67456251/85919346-94c1e280-b86a-11ea-9607-de4f925d1d9b.png)

Das funktioniert auch. Der Switch-Node gibt - entsprechend Tastendruck des Smartbutton - das weiter. An der Stelle, muss wahrscheinlich noch etwas dazwischen und (sage mal laienhaft) der den Wert "formatiert" (einfache wie bei einem Injekt-Node) oder ein Change-Switch der in passendere Werte konvertiert.

**Comment by get-command** [comment]
Der Execute-Button am Zigbee-Gerät funktioniert problemlos...

![grafik](https://user-images.githubusercontent.com/67456251/85919437-5aa51080-b86b-11ea-9c33-f0ea934a6a3e.png)

**Comment by stuckis6er** [comment]
Tausch doch bitte mal die beiden Licht Nodes.

**Comment by get-command** [comment]
> Ohne Debug Message bin ich raus

Meinst Du das?



> Tausch doch bitte mal die beiden Licht Nodes.

Hab ich. Ändern leider nix.

**Comment by Sineos** [comment]
Ersetze den Inhalt der Function Node durch:
```
const msg2;
msg2 = {};
msg2.payload = msg.payload;
return msg2;
```

**Comment by Sineos** [comment]
Bzw. das reicht vermutlich noch nicht. Du sagst die Inject Nodes funktionieren. Was ist der Inhalt des Injects?

**Comment by get-command** [comment]
> 
> 
> Bzw. das reicht vermutlich noch nicht. Du sagst die Inject Nodes funktionieren. Was ist der Inhalt des Injects?

Ich habe an den Inject-Node nichts verändern. Er sendet ja im Default ja den Timestamp. Damit gehts. Habe spaßeshalber mal auf Bolean True gestellt, auch das geht.

Der von dir o.g. Code ist fehlerhaft. Die Variable ist undefiniert oder so ähnlich war die Fehlermeldung.

Gibt es irgendwie eine Äquivalent zum Inject-Node mit einem Input?

**Comment by get-command** [comment]
> 
> 
> Setze mal zwischen "Smart Button" und Switch-Node eine Function-Node mit folgendem Inhalt:
> 
> ```
> msg = {};
> msg.payload = true;
> return msg;
> ```

DAS WAR ES!!!!!!!!!!!!!!!!!! Was für eine schwere Geburt :-) Vielen Dank Dir und allen anderen für die Hilfe!

Ich habe diesen function-Node zwischen Switch und Lampe eingebaut. Damit hat es tatsächlich funktioniert. Danke!!danke! danke!

**Comment by Sineos** [comment]
Fein. Erklärung ist folgende:

- Wie du oben in der Debug Node gesehen hast, besteht eine `msg` nicht nur aus dem Payload-Attribut sondern kann ganz viele andere Attribute haben, z.B. `endpoint`, `cluster`, `ieeeAdr` usw.
- In Node-Red ist es gemeinhin so, dass du solche Attribute entweder in einer Node definieren kannst (z.B. in deiner "zigbee osram light on") **ODER** die Eigenschaften mit einer `msg` übergeben kannst

Die Quelle deiner `msg` ist die "smartbutton zigbee" Node. Da es auch ein zigbee Gerät ist, enthalten seine `msg` Objekte **seine** `endpoint`, `cluster`, `ieeeAdr` usw. Informationen. Diese knallst du dann in die Osram Node und überschreibst mit diesen die Einstellungen der Osram-Node.

Der Function-Schnipsel macht nichts anderes als alle Attribute zu löschen und nur das Payload-Attribut auf `true` zu setzen.

Bitte hier dann zu machen wenn es für dich gelöst ist.

**Comment by get-command** [comment]
> Bitte hier dann zu machen wenn es für dich gelöst ist.

Ich habe mir das schon, so wie Du das erklärt hast, vorgestellt. Es ist logisch und plausibel. Bin in  der Thematik relativ neu noch. 

Vielen Dank für die hervorragende Beschreibung!
