### ISSUE TITLE
MQTT-Explorer/MQTT.fx

### ISSUE THREAD

**Issue by get-command** [hobbyquaker/node-red-contrib-zigbee#114]
Hallo Experten,

weiß einer zufällig, was ich machen muss, um die Topics zu subscriben? Ich konnte bei meinen Funkgeräten das problemlos einrichten, bei zigbee2mqtt in Konstellation mit diesen Nodes habe ich es nicht hinbekommen. 

Ich habe in einem anderen Forum erfahren, dass man in der configuration.yaml normalerweise seine gejointen Geräte findet. Bei mir enthält die Datei /opt/zigbee2mqtt/data/configuration.yaml keinen Punkt "devices". Ich habe jede Menge Geräte über die Nodes gepairt, aber die erscheinen in dieser Datei nicht. Muss ich das manuell machen oder gibt es bei diesen Nodes eine andere Vorgehensweise?

Ich hatte z.B. in Debugfenster bei einem Zigbee-Device diesen Eintrag:

zigbee/0x7cb03eaa00a7xxx

Wenn ich das aber als Topic in den MQTT-Programm aufnehme, passiert nix.

Debug im Node-Red:

![grafik](https://user-images.githubusercontent.com/67456251/86108675-be297b00-bac3-11ea-963e-a1016749e4d3.png)

Diesen Topic habe ich übernommen, aber es passiert nicht:
![grafik](https://user-images.githubusercontent.com/67456251/86109129-532c7400-bac4-11ea-8d1f-33f9819c0bab.png)

**Comment by Sineos** [comment]
Bei der Verwendung node-red-contrib-zigbee findet die Kommunikation Node-Red intern statt und nicht über MQTT. Wenn du zusätzlich MQTT verwenden möchtest, muss das über die Node-Red MQTT Nodes realisiert werden.

**Comment by get-command** [comment]
> Bei der Verwendung node-red-contrib-zigbee findet die Kommunikation Node-Red intern statt und nicht über MQTT. Wenn du zusätzlich MQTT verwenden möchtest, muss das über die Node-Red MQTT Nodes realisiert werden.

Hallo Sineos,

sei gegrüßt...

 Ich dachte, da das auf dem zigbee2mqtt-Stick basiert, werden die "internen" Abläufe mittels mqtt "übersetzt". So kann man sich irren :-)

Danke für die Info!
