### ISSUE TITLE
Gleichzeitige Nutzung MQTT

### ISSUE THREAD

**Issue by get-command** [hobbyquaker/node-red-contrib-zigbee#116]
Hallo Forum, 

Ich hatte ja bereits kürzlich angefragt gehabt, wie ich mit den MQTT und diesen Nodes arbeiten kann. Ein sehr aufmerksamer User hatte mich aufgeklärt, dass diese Nodes die Kommunikation intern nutzen und nicht über den MQTT-Server...

Jetzt zu meiner Frage:
Hat jemand schonmal parallel auch die Geräte über MQTT und nach der Anleitung von zigbee2mqtt.to eingebunden?? Kürzer: ist ein Parallelbetrieb möglich bzw. muss dafür etwas spezieller konfiguriert werden??

Vielen Dank für die Hilfe!

**Comment by kneip68** [comment]
Da beide Implementationen den Serial Port des USB Sticks reservieren, ist meines Wissens nach keine Parallele Nutzung möglich (jedenfalls ohne "Handstände")

**Comment by Sineos** [comment]
Parallel node-red-contrib-zigbee und zigbee2mqtt nutzen geht nicht.

zigbee2mqtt besteht im prinzip aus 3 "Komponenten"
- zigbee-herdsman: Unterstützung der Hardware und des zigbee-Protokolls
- zigbee-herdsman-converters: Unterstützung der verschiedenen zigbee-Geräte
- zigbee2mqtt:  Kommunikation und Steuerung über das MQTT-Protokoll

Die einzige Möglichkeit ist, mit den Node-Red eigenen MQTT-Nodes, quasi seine eigene MQTT Logik nachzubilden. Der einfachste Fall wäre zigbee-Converter-Node direkt auf eine MQTT-Out Node zu hängen.

**Comment by get-command** [comment]
Vielen Dank für die Infos... 

Wie immer sehr detailliert und verständlich erklärt.
