### ISSUE TITLE
Nach Entfernung, ist eine erneute Verbindung nicht möglich

### ISSUE THREAD

**Issue by get-command** [hobbyquaker/node-red-contrib-zigbee#123]
Hallo Forum,

mir ist bei zwei Geräten aufgefallen, nachmdem ich sie gelöscht habe, nicht nochmal Joinen konnte. Ein Neustart hat auch nicht geholfen. Muss dabei etwas Spezielles beachtet werden? Es handelt sich dabei um Osram E14 Lampen. Die Ersteinbindung ist nie ein Problem, funktioniert tadellos.

Danke für Eure Hilfe.

**Comment by get-command** [comment]
Hat keiner eine Idee?

**Comment by stuckis6er** [comment]
Leider hab ich keine Idee aber ohne log-Datei wird da auch kaum jemand helfen können.

Gruß

**Comment by Sineos** [comment]
Hast du die Lampe korrekt resetted? Hat sie den Rest bestätigt? Anlernen nahe genug am Coordinator?

**Comment by get-command** [comment]
> 
> 
> Hast du die Lampe korrekt resetted? Hat sie den Rest bestätigt? Anlernen nahe genug am Coordinator?

Manchmal ist es einfacher als gedacht :-)

Ich wußte nicht, dass man so eine Osram Smart+ Lampe auf Werkseinstellungen zurücksetzten kann. Geht tatsächlich mit: 5x 3 Sekunden AN und 5 Sekunden aus.

Danke nochmal - Thread kann geschlossen werden.

**Comment by Sineos** [comment]
@get-command 
Generell müssen Zigbee Geräte resetted werden, wenn sie abgelernt wurden und wieder neu angelernt werden sollen.

Bitte hier zu machen, wenn Dein Thema gelöst ist. Das kannst nur Du als Ersteller oder @hobbyquaker
