### ISSUE TITLE
Redmatic Conbee II Controller-Node "Status: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'" 

### ISSUE THREAD

**Issue by ppcfox** [hobbyquaker/node-red-contrib-zigbee#125]
Auf meiner CCU3 läuft das Addon CUxd und Redmatic. In CUxd habe ich den seriellen Port deaktiviert (TTYASSIGN=ttyACM0:NC). Beim Hinzufügen des Controller-Nodes erhalte ich die oben aufgeführte Fehlermeldung.
Auch wird scheinbar ein Teil der Konfiguration des Nodes nicht gespeichert.  Die Auswahl des Adapters "ConBee" wird wieder auf "Z-Stack" zurückgestellt. Andere Einstellungen bleiben erhalten.

Was ich bereits gemacht habe: 
-Stick abgezogen, wider angesteckt
-CCU3 neu gestartet
-Konfiguration entfernt und neu erstellt

Vielleicht kann mir ja jemand helfen.

**Comment by Sineos** [comment]
Vorher einen anderen zigbee Controller / Stick gehabt?

**Comment by ppcfox** [comment]
Lediglich einen USB-Speicherstick, aber kein Funkmodul.

**Comment by dschido** [comment]
Hallo,

hast Du es schon einmal ohne den USB Stick probiert? Ich hatte die gleiche
Meldung einmal nach einem Stromausfall und da lief es erst nach einem
Neustart nur mit dem Zigbee Stick.

ppcfox <notifications@github.com> schrieb am Mi., 16. Sept. 2020, 19:50:

**Comment by ppcfox** [comment]
Vielen Dank für eure Antworten. Leider hat das alles nicht zum Erfolg geführt. Ich muss wohl noch weiter mit Deconz leben. Funktioniert ja, aber ich habe eben wieder einen weiteren Server.

**Comment by Sineos** [comment]
Diese Fehlermeldung heißt alles und nix. Bekommst auch wenn Du von einem Controller auf einen anderen wechselst und die PanID nicht änderst.

Folgendes kannst probieren:
- Redmatic Log hier anhängen
- Auf jedenfall die PanID im Vergleich zum Deconz Netzwerk wechseln
- Darauf achten, dass PanID (4 stellig) und Schlüssel (32 stellig) gültige Hex Zahlen (A-F und 0-9) sind
- CuxD ganz runter werfen

**Comment by ppcfox** [comment]
Hallo Sineos,
alles probiert, immer wieder der selbe Fehler. Log habe ich mal angehangen.
[redmatic.2020-09-17T18_47_19.182Z.log](https://github.com/hobbyquaker/node-red-contrib-zigbee/files/5241304/redmatic.2020-09-17T18_47_19.182Z.log)

**Comment by Sineos** [comment]
Das Log ist recht sparsam. Kannst du Redmatik mal auf Debug setzen und ein neues Log produzieren?
Macht das RTSCTS Setting einen unterschied?

**Comment by ppcfox** [comment]
Hallo Sineos,
vielen Dank schon mal, dass du dich der Sache annimmst. Ich hab das Ganze nochmals, im Debug-Mode, durchgespielt und auch mal versucht den RTSCTS auf "false" zu setzen - hat alles nichts gebracht. Anbei nochmal das Log.

[redmatic.2020-09-19T17_35_35.639Z.log](https://github.com/hobbyquaker/node-red-contrib-zigbee/files/5250302/redmatic.2020-09-19T17_35_35.639Z.log)

**Comment by Sineos** [comment]
Aus dem Log geht auch nichts erhellendes hervor.

Ich nehme mal an, du hast verifiziert, dass `/dev/ttyACM0` richtig ist? (ich kenne den Conbee stick nicht, aber die TI Launchpads haben zwei ttyACM und zzh ist eine /dev/USBx device)

So wie ich das Log lese, kommt schon gar keine Kommunikation zwischen NR-zigbee und dem Conbee zustande. Das ist schon ein bisschen seltsam.
In der letzten Zeit gabs ein paar Verbesserungen im herdsman bzgl. dem Conbee, die aber noch nicht in NR-zigbee eingeflossen sind. Das sollte aber nicht diese totale Verweigerungshaltung erklären.

Du könntest schauen ob `dmesg` und / oder `lsusb` (via SSH)  und / oder `ls -l /dev/ttyACM*` irgendwelche Schmerzen mit dem Conbee anzeigen würden.
In Windows scheint das Ding einen eigenen Treiber zu brauchen, vielleicht fehlt dieser ja in der Raspberrymatik-Version von @Jens-Maus. Darüber hinaus hab ich jetzt auch keine Ideen mehr.

Generell würde noch gelten, bei Experimenten öfter den Stick zu ziehen und wieder zu stecken und auch bei Änderungen der Einstellungen in der NR-zigbee Config, NR komplett neu zu starten. Darüber hinaus hab ich jetzt auch keine Ideen mehr.

**Comment by ppcfox** [comment]
Hallo Sineos,
vielen Dank für deine Hilfe. Ich habe mittlerweile einen "factory reset" durchgeführt und RedMatic neu installiert.
Hat alles nichts geholfen. Ich werde jetzt erst mal abwarten bis da eine neue Version rausgekommen ist und so lange mit meinem ioBroker weiter machen. Ich scheine auch nicht der Einzige zu sein ([siehe hier](https://homematic-forum.de/forum/viewtopic.php?t=60218&p=602880)), der die Probleme hat. Vielleicht fehlt ja tatsächlich noch was.
Ich werde das hier erst mal schließen.

Gruß Jörg

**Comment by Sineos** [comment]
@ppcfox 
Probier mal noch bitte Folgendes:
- Node-Red beenden
- Via SSH auf deiner RasperryMatic einloggen
- `sed -i 's/<select id="adapter">/<select id="node-config-input-adapter">/g' /usr/local/addons/redmatic/lib/node_modules/node-red-contrib-zigbee/nodes/shepherd.html` ausführen
- NR starten
- Deconz als Adapter wählen & deploy
- NR neu starten

**Comment by ppcfox** [comment]
werde ich machen, komme aber erst am Mittwoch dazu, da ich beruflich gerade unterwegs bin.

**Comment by ppcfox** [comment]
@Sineos 
Hallo Sineos, es hat tatsächlich funktioniert. Vielen Dank nochmals für deine Hilfe.

<img width="244" alt="Bildschirmfoto 2020-09-23 um 18 49 58" src="https://user-images.githubusercontent.com/42517624/94043824-afeeb080-fdcd-11ea-86d5-2df4512b35c9.png">

**Comment by Sineos** [comment]
Klasse. Danke für die Rückmeldung
