### ISSUE TITLE
v0.20 not showing up in Node-RED palette

### ISSUE THREAD

**Issue by bohtho** [hobbyquaker/node-red-contrib-zigbee#131]
Why isn't 0.20 showing as an available update from 0.19 in my Node-RED ?

**Comment by spiu16** [comment]
The package needs to be included in the next RedMatic version and cannot be installed via the palette.

**Comment by bohtho** [comment]
Thanks for the reply. Do you mean “next Node-RED” version ? I have used this package and the redmatic-homekit package independently from the rest of redmatic.

**Comment by spiu16** [comment]
Mhmm, no, I certainly my meant redmatic. Not sure how it works independently.

**Comment by Sineos** [comment]
`node-red-contrib-xxx` packages need to be published on https://flows.nodered.org/ and on https://www.npmjs.com/.
If you check zigbee package there (https://flows.nodered.org/node/node-red-contrib-zigbee / https://www.npmjs.com/package/node-red-contrib-zigbee) you will see the latest published version is 0.19 on flows.nodered.org and 0.20 on npmjs.com.
It looks like @hobbyquaker missed to publish the 0.20 version on flows.nodered.org and thus the package will not appear in Node-Red's palette.
