### ISSUE TITLE
CC2538 + CC2592 - Zigbee dongle - ZB3.0

### ISSUE THREAD

**Issue by maciekelga** [hobbyquaker/node-red-contrib-zigbee#132]
Hi,
is it working with CC2538 + CC2592 - Zigbee dongle - ZB3.0?
https://www.tindie.com/products/GiovanniCas/cc2538-cc2592-zigbee-dongle-zb30/

I like to use it with Node Red to get a readings from battery sensors.

**Comment by Sineos** [comment]
Yes, this dongle is compatible to zigbee2mqtt so it should work in node-red-contrib-zigbee as well.
You can get a list of supported adapters here: https://www.zigbee2mqtt.io/information/supported_adapters.html

**Comment by maciekelga** [comment]
Thank You very much.

**Comment by Sineos** [comment]
Welcome. Please close the topic unless you need to add further to it
