### ISSUE TITLE
After update to raspberrymatic 7.2 and zigbee 0.20.3 all paired devices are gone

### ISSUE THREAD

**Issue by hdiessner** [hobbyquaker/node-red-contrib-zigbee#148]
Yesterday, I upgraded Raspberrymatic to 7.2.0 and subsequently to 7.2.1.
Node-red-contrib-zigbee is verion 0.20.3.

After the upgrade, all paired zigbee devices are gone.
Even after restart and shutdown and complete removal of power supply, all zigbee devices are not there.

PanID et. al. seem to be ok.

Any hint how to get back the paired devices or is a fresh pairing of all devices necessary?

**Comment by Sineos** [comment]
Strange, worked for me without loosing the devices.
I had some occasions where my devices where lost and I could not get them back (although I had a backup of the `dev.db`)

My advice would be to assign a new `panID` and start over

**Comment by hdiessner** [comment]
So I started over, now all my devices are back online again; whysoever that happened...
