### ISSUE TITLE
lidl zigbee bewässerungscomputer

### ISSUE THREAD

**Issue by tromanski** [hobbyquaker/node-red-contrib-zigbee#155]
Hallo Zusammen,

ich habe heute einen cc2531 Stick an meine Redmatic angeschlossen und konfiguriert. Scheint auch soweit zu funktionieren.
Nun versuche ich meinen Lidl Zigbee Bewässerungscomputer (https://www.lidl.de/p/parkside-smarter-bewasserungscomputer-zigbee-smart-home/p100325201) zu verbinden. Als Device wird das Gerät in der Geräteliste angezeigt, jedoch bekomme ich folgende Debug Meldung: Received message from unsupported device with Zigbee model 'TS0601' Die zweite Meldung lautet: Please see: https://www.zigbee2mqtt.io/how_tos/how_to_support_new_devices.html

Kann mir jemand einen Hinweis geben, wie dieses Gerät verwendet werden könnte?

Ich danke euch im Voraus

**Comment by jokakilla** [comment]
Hi,
node-red-contrib-zigbee nutzt die zigbee-herdsman-converts von Koenkk. Dort kam die Unterstützung für das Gerät erst ende Juni rein. Siehe: https://github.com/Koenkk/zigbee-herdsman-converters/commit/ee05bb1ee3d271313d801445c6ec9b2f6bc60aaa#diff-9f95626d459809420576fa9d9e45a723238c91c0b9c2d86a9ff3573d3559e3ab

Da es seit März kein Update der Abhängigkeit auf die neusten zigbee-herdsman-converters gab lässt sich das Gerät über die Converter aktuell nicht nutzen. Evtl. kannst du es direkt mit Commands versuchen.

Ich hab mir schon sorgen gemacht weil man von hobbyquaker seit März quasi nix gehört hat. Hier -> https://github.com/hobbyquaker/node-red-contrib-zigbee/issues/154 versuche ich gerade selbst die Abhängigkeiten zu aktualisieren. Es ist allerdings nicht mit einer neuen Versionsnummer getan weil sich offenbar ein bisschen was an der Schnittstelle zwischen node-red-contrib-zigbee und zigbee-herdsman-converters geändert hat.

Ich hab leider nicht so sehr viel Hardware zum Testen aber in meiner Umgebung funktionierte es schon ganz gut, sodass ich evtl. morgen Abend einen Pull Request stellen kann. Vielleicht meldet sich Hobbyquaker dann ja noch und kann das Update integrieren.

**Comment by tromanski** [comment]
Hi,
danke für die Hinweise und deine Mühe die Abhängigkeiten zu aktualisieren! Bin sehr gespannt auf das Update von Hobbyquaker.  Bis dahin würde ich gerne den Umweg, wie von dir vorgeschlagen, über Commands machen. 
Ich habe im "Commands"-Node etwas zusammengeklickt, bin mir aber nicht so sicher was ich genau eintragen soll. Bei meinem Versuch kommt folgender Fehler (siehe Bild). Kannst du etwas damit anfangen und mir eventuell einen Hinweis geben, was ich ändern muss?

![image](https://user-images.githubusercontent.com/59796315/129473798-c3c4bb86-43a1-41cd-9333-7f152c101c4a.png)

**Comment by jokakilla** [comment]
Mit dem Command Node habe ich auch noch nichts weiter gemacht.
Ein Read für den aktuellen Zustand habe ich so hin bekommen:
![grafik](https://user-images.githubusercontent.com/18099752/129487374-6139ad52-9b2e-4cca-8838-51d1da8b10d1.png)

Das Write klappt aber irgendwie nicht. Kommt immer die Meldung das Attribut sei Read-Only.
![grafik](https://user-images.githubusercontent.com/18099752/129487415-f50fd9a9-95e0-4414-9d9d-9cf804bd4044.png)

**Comment by tromanski** [comment]
Hallo  jokakilla,
leider funktionieren bei mir weder "read" noch "write". Kannst du mit der Meldung etwas anfangen?
![image](https://user-images.githubusercontent.com/59796315/130112903-747a5c7e-0c92-4a3d-a72a-186cdcbe2c07.png)

Gibt es schon Fortschritte bei deinem Pull Request?

**Comment by jokakilla** [comment]
Gestellt habe ich ihn schon. Jetzt muss er nur noch für gut genug befunden und integriert werden ;)

https://github.com/hobbyquaker/node-red-contrib-zigbee/pull/157

Ich hoffe jemand pflegt das Projekt weiter. In den letzten Monaten war es hier verdammt ruhig.

**Comment by jokakilla** [comment]
Hast Du bei deinem controller rtscts auf true gesetzt? Den Hinweis hatte ich hier gelesen -> https://github.com/Koenkk/zigbee2mqtt/issues/2500

Bei mir hat gerade folgendes mit einem CC2531 funktioniert

![grafik](https://user-images.githubusercontent.com/18099752/130354639-f963b703-cdb9-441e-b820-362049a842e1.png)

**Comment by tromanski** [comment]
Hallo Zusammen,

gute Nachrichten. Nachdem seit August etwas Zeit vergangen ist, habe ich einen neuen Versuch zur Eröffnung der Gartensaison gewagt. In der Zwischenzeit wurden einige Updates installiert und siehe da, der Bewässerungscomputer funktioniert ohne Modifikationen! Lediglich die maximale Bewässerungszeit muss vorher über die offizielle App eingestellt werden.
