### ISSUE TITLE
allready install and runnin the zigbee2mqtt ,  Can I use this isntalation with node red-contrib-zigbee

### ISSUE THREAD

**Issue by joseluisgodinho** [hobbyquaker/node-red-contrib-zigbee#2]

**Comment by hobbyquaker** [comment]
You can't run them at the same time, only one shepherd can connect to your zigbee interface. But what you can do: deploy the shepherd node, wait a while, reconfigure it - make sure that it has the same `panId` and `precfgkey` setting like you're zigbee2mqtt, deploy again. Then stop node-red and zigbee2mqtt and copy the `dev.db` file from zigbee2mqtt to `~/.node-red/zigbee/<shepherd-node-id>/` and start node-red again. Now all devices should appear in the devices node and you play around with node-red-contrib-zigbee. When you want to move back to zigbee2mqtt just stop node-red and start zigbee2mqtt again.

**Comment by joseluisgodinho** [comment]
Hello

I just made the following
1) panId & precfgkey
           my data/configuration.yaml, dont have those values registerd therefor i used yourby default - OK
2) Copy File dev.db
         It dididn´t work as you mentioned . the file in question is database.db, and i copied to the the mentioned folder.

I have it working now!

I am going to try it out, and thankyou for your time
JLG
