### ISSUE TITLE
keine Statusmeldung von Osram smart plug

### ISSUE THREAD

**Issue by dschido** [hobbyquaker/node-red-contrib-zigbee#20]
Hallo Hobbyquaker,

die Osram smart plug Steckdose scheint keine Statusmeldung abzugeben, wenn das Gerät geschaltet wird, oder ob es geschaltet hat.

Kannst man das noch einbauen?

Danke

**Comment by hobbyquaker** [comment]
Schau mal ob es mit node-red-contrib-zigbee 0.4.5 bzw. RedMatic 4.3.7 funktioniert.

**Comment by dschido** [comment]
Mit 4.3.7 bekomme ich jetzt eine Rückmeldung wenn ich die Steckdose per Funk schalte. Wenn ich aber direkt am Gerät über die Taste schalte, bekomme ich leider immer noch keine Status Meldung.

**Comment by hobbyquaker** [comment]
Hmm, dann befürchte ich dass das Gerät in dem Fall einfach nichts zurückmeldet. Das könntest Du mal auf Log Level Debug überprüfen, da siehst Du alle vom Zigbee-Shepherd eingehenden Nachrichten.

**Comment by hobbyquaker** [comment]
Ah, ich glaub ich weiss was ich da übersehen habe. Man muss das reporting für das device konfigurieren, gib mir ein bisschen Zeit das zu checken. https://github.com/Koenkk/zigbee-shepherd-converters/blob/48ddc6c08c159b3663cf4619e10c227dcee182b9/devices.js#L1217

**Comment by dschido** [comment]
gerne. Aber im log steht nichts...

**Comment by hobbyquaker** [comment]
node-red-contrib-zigbee 0.5.0 (enthalten in RedMatic 4.3.8) sollte nun den Plug konfigurieren. Halte mal Ausschau nach einer Log Meldung `successfully configured` und gib Bescheid ob es funktioniert.

**Comment by dschido** [comment]
funktioniert perfekt: sowohl event als auch converter liefern nun ein StatusReport wenn die Steckdose geschaltet wird:

{"topic":"zigbee/xxx","payload":{"state":"ON"},"name":"Küche_OSRAM01","type":"Router","manufName":"OSRAM","modelId":"Plug 01","ieeeAddr":"xxx","cid":"genOnOff","data":{"onOff":1},"_msgid":"6274f799.742a58"}

Vielen Dank
super support

**Comment by Starkstroemer** [comment]
Hallo,

bin leider noch nicht so fit in Node Red...aber es wird.

Wie kann ich denn aus diesem State meiner Osram+ das "on" vom State extrahieren? Ich möchte ja gerne wissen ob die Steckdose schon an ist wenn ich die Node Red UI öffne. Aktuell ist es so, das ich entweder per Taster an der Steckdose, Aqara Taster oder UI schalten kann. Und leider aktualisiert sich der Status ja nicht, sofern ich nicht über die UI geschaltet habe.

{"e":"changed","id":"2","r":"lights","state":{"on":true,"reachable":true},"t":"event","uniqueid":"7c:b0:3e:aa:0a:08:68:5f-03"}
