### ISSUE TITLE
Configuring the shepherd node

### ISSUE THREAD

**Issue by spiu16** [hobbyquaker/node-red-contrib-zigbee#21]
Hi,

what settings do I need to configure exactly? Which ones do I need to change? Which channels do I have to select?
I want to connect IKEA Tradfri devices and got to work with the instructions from https://www.zigbee2mqtt.io/, but I wasn't able to get to to work with the node-red-contrib-zigbee.

Thanks and regards

**Comment by hobbyquaker** [comment]
If you want to keep the pairing you already did with zigbee2mqtt see https://github.com/hobbyquaker/node-red-contrib-zigbee/issues/2

If you want to start from scratch defaults should be fine, change the precfgkey for security reasons (see https://github.com/hobbyquaker/node-red-contrib-zigbee/blob/master/README.md#shepherd)

**Comment by spiu16** [comment]
okay thanks. I used a separate RaspberryPi for the existing configuration with zigbee2mqtt. does it make any difference for [#2](https://github.com/hobbyquaker/node-red-contrib-zigbee/issues/2)?

**Comment by hobbyquaker** [comment]
The CC253x has to have the same ieeeAddr. So if you use the same USB Stick it should make no difference.

**Comment by spiu16** [comment]
Hi,
I tried to start from the scratch (since I had only connected an IKEA remote so far). I plugged in the CC2531 USB sniffer to the RaspberryMatic, used the "devices"-node, configured the shepherd node and deployed. But I get the error message

> 30.4.2019, 22:38:08node: zigbee shepherd
msg : string[25]
"request timeout, retrying"

Any idea what I do wrong?

Thanks

**Comment by spiu16** [comment]
One more thing: I had installed the [mosquitto addon](https://github.com/hobbyquaker/ccu-addon-mosquitto) before to connect from zigbee2mqtt. Do I still need this addon with node-red-contrib-zigbee?

**Comment by hobbyquaker** [comment]
Nope, node-red-contrib-zigbee doesn't depend on MQTT. It can play well with it, but it's up to you if you want to use it ;-)

**Comment by spiu16** [comment]
Ok, and any idea about the error message? :-)

**Comment by dschido** [comment]
I got the same message, because usb port was used by cuxd. Maybe you have the same issue?

**Comment by hobbyquaker** [comment]
what does `ls /dev/tty*` say?

**Comment by spiu16** [comment]
`# ls /dev/tty*
/dev/tty        /dev/tty23      /dev/tty39      /dev/tty54
/dev/tty0       /dev/tty24      /dev/tty4       /dev/tty55
/dev/tty1       /dev/tty25      /dev/tty40      /dev/tty56
/dev/tty10      /dev/tty26      /dev/tty41      /dev/tty57
/dev/tty11      /dev/tty27      /dev/tty42      /dev/tty58
/dev/tty12      /dev/tty28      /dev/tty43      /dev/tty59
/dev/tty13      /dev/tty29      /dev/tty44      /dev/tty6
/dev/tty14      /dev/tty3       /dev/tty45      /dev/tty60
/dev/tty15      /dev/tty30      /dev/tty46      /dev/tty61
/dev/tty16      /dev/tty31      /dev/tty47      /dev/tty62
/dev/tty17      /dev/tty32      /dev/tty48      /dev/tty63
/dev/tty18      /dev/tty33      /dev/tty49      /dev/tty7
/dev/tty19      /dev/tty34      /dev/tty5       /dev/tty8
/dev/tty2       /dev/tty35      /dev/tty50      /dev/tty9
/dev/tty20      /dev/tty36      /dev/tty51      /dev/ttyACM0
/dev/tty21      /dev/tty37      /dev/tty52      /dev/ttyS0
/dev/tty22      /dev/tty38      /dev/tty53      /dev/ttyprintk
`

**Comment by spiu16** [comment]
> I got the same message, because usb port was used by cuxd. Maybe you have the same issue?
> 
> If yes edit configuration:
> TTYASSIGN=ttyACM0:NC

Where do I edit the configuration?

Now I get the status "closing":
![image](https://user-images.githubusercontent.com/45998371/57036270-1a8cd280-6c54-11e9-86af-fbab269211fb.png)

**Comment by hobbyquaker** [comment]
to clarify: you have 1 USB-Stick for Backup and the CC2531 connected? Nothing else? Please log in to your ccu via ssh and show the output of `ls /dev/tty*`

**Comment by spiu16** [comment]
Correct, 1 USB-Stick and the CC2531. Nothing else. Output of ls /dv/tty*:

> /dev/tty /dev/tty23 /dev/tty39 /dev/tty54
/dev/tty0 /dev/tty24 /dev/tty4 /dev/tty55
/dev/tty1 /dev/tty25 /dev/tty40 /dev/tty56
/dev/tty10 /dev/tty26 /dev/tty41 /dev/tty57
/dev/tty11 /dev/tty27 /dev/tty42 /dev/tty58
/dev/tty12 /dev/tty28 /dev/tty43 /dev/tty59
/dev/tty13 /dev/tty29 /dev/tty44 /dev/tty6
/dev/tty14 /dev/tty3 /dev/tty45 /dev/tty60
/dev/tty15 /dev/tty30 /dev/tty46 /dev/tty61
/dev/tty16 /dev/tty31 /dev/tty47 /dev/tty62
/dev/tty17 /dev/tty32 /dev/tty48 /dev/tty63
/dev/tty18 /dev/tty33 /dev/tty49 /dev/tty7
/dev/tty19 /dev/tty34 /dev/tty5 /dev/tty8
/dev/tty2 /dev/tty35 /dev/tty50 /dev/tty9
/dev/tty20 /dev/tty36 /dev/tty51 /dev/ttyACM0
/dev/tty21 /dev/tty37 /dev/tty52 /dev/ttyS0
/dev/tty22 /dev/tty38 /dev/tty53 /dev/ttyprintk

**Comment by hobbyquaker** [comment]
can you pls show a screenshot of your shepherd configuration? should look smth like this:
![image](https://user-images.githubusercontent.com/2503307/57038553-7a867780-6c5a-11e9-9f1e-3ba6a48887cd.png)

And did you follow Dschidos tip? Do you have CUxD running?

**Comment by spiu16** [comment]
My configuration:
![image](https://user-images.githubusercontent.com/45998371/57038708-dc46e180-6c5a-11e9-97f8-f155f560410a.png)

How do I edit the configuration for Dschidos tip? (TTYASSIGN=ttyACM0:NC)

**Comment by hobbyquaker** [comment]
I have no CUxD, so I'm not sure, but iirc there was some possibility in the cuxd webui to set config params. maybe @dschido can help here.

**Comment by dschido** [comment]
Cuxd configuration must be done in cuxd subpage. http://http://ccu3-webui/addons/cuxd.
Put this line in the setup

**Comment by spiu16** [comment]
Great! this works! thanks @hobbyquaker  and @dschido for the support.
I added the line to the CUxD-setup, restarted CUxD and NodeRed and it worked:
![image](https://user-images.githubusercontent.com/45998371/57156799-3375bf00-6ddf-11e9-825f-c1a4d075d69d.png)
![image](https://user-images.githubusercontent.com/45998371/57156813-3a9ccd00-6ddf-11e9-8fd1-a2dce0aa62ce.png)

**Comment by SkylightXD** [comment]
Are you able to connect the TRÅDFRI remote controll?

**Comment by spiu16** [comment]
Yes! Press the pairing button 4x while holding the remote close to the CC2531. That‘s how I got them paired.

**Comment by SkylightXD** [comment]
Jeah!!! Thanks a lot!
Pressing the pairing button 4x within 5 seconds reset the remote, but also connect it, while the device node is ready to join! :D

Do you know if it is possible to reset a hue lamp by the TRÅDFRI remote? So like the hue dimmer do it?

**Comment by spiu16** [comment]
sorry, I don’t know. I don’t have hue devices.

**Comment by RoyBoy79** [comment]
> Cuxd configuration must be done in cuxd subpage. http://ccu3-webui/addons/cuxd.
> Put this line in the setup

Hi, having similar Problems with the CCU3. What line can I put in the setup?

**Comment by RoyBoy79** [comment]
> > Cuxd configuration must be done in cuxd subpage. http://ccu3-webui/addons/cuxd.
> > Put this line in the setup
> 
> Hi, having similar Problems with the CCU3. What line can I put in the setup?

I added "**TTYASSIGN=ttyACM0:NC**""
