### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Zabov79** [hobbyquaker/node-red-contrib-zigbee#3]
The following is the error I got when tried to install:
```

root@raspberrypi:/home/pi# npm install node-red-contrib-zigbee
npm ERR! code ENOGIT
npm ERR! Error while executing:
npm ERR! undefined ls-remote -h -t https://github.com/Koenkk/zigbee-shepherd.git
npm ERR! 
npm ERR! undefined
npm ERR! No git binary found in $PATH
npm ERR! 
npm ERR! Failed using git.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-01-30T15_55_58_392Z-debug.log
```

**Comment by hobbyquaker** [comment]
Git is missing, try `sudo apt install git make build-essential`

**Comment by tweaker** [comment]
How to turn it in docker?

**Comment by CyberAndi** [comment]
Servus, auch bei mir geht auf dem RaspberryMatic die Installation von ZigBee-Contrib nicht. 'Es wird nicht mal ein Verzeichnis angelegt. es kommen nur ERR-Meldungen. aber der Convertzer wird in einem Extra Verzeichnis angelegt, aber es wird kein Packet erstellt.
