### ISSUE TITLE
join hue light by serial number

### ISSUE THREAD

**Issue by SkylightXD** [hobbyquaker/node-red-contrib-zigbee#31]
Hi hobbyquaker,

ich habe gebrauchte Hue Lights gekauft und möchte diese über CC2531 -> CCU3 -> Redmatic -> node-red-contrib-zigbee ansprechen. Das hat bei der ersten auch wunderbar funktionert, aber bei der zweiten nicht. 
Daher würde ich diese gerne auf die Werkseinstellungen zurück setzen. Ich habe keine Hue oder TRÅDFRI Fernbedienung, aber ich habe gelesen, dass man diese auch an der Hue Bridge mittels Seriennummer Verbinden und damit resetten kann. Geht das auch mit deinem node?

Danke und Grüße
Christoph

**Comment by hobbyquaker** [comment]
Leider nein. Der günstigste Weg eine Hue Lampe zu resetten ist wohl im Moment diese Fernbedienung: https://www.amazon.de/Philips-Hue-Wireless-komfortabel-Installation/dp/B0748KLR39/ref=sr_1_3?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&keywords=hue+fernbedienung&qid=1556914313&s=gateway&sr=8-3 (hab neulich eine in einem Sonderangebot mit einer E27 Hue White für 20€ bekommen)

**Comment by SkylightXD** [comment]
Angeblich geht es auch mit der Ikea Fernbedienung:[TRÅDFRI Fernbedienung](https://www.ikea.com/de/de/p/tradfri-fernbedienung-30338849/)

Hast du das schon probiert? ;)

Danke für den Hinweis :)

**Comment by hobbyquaker** [comment]
Nope, hab ich bisher nicht getestet.

**Comment by SkylightXD** [comment]
Aber meine Vermutung ist richtig, dass wenn die Lampe einmal mit einer Bridge verbunden wurde, muss ich die erst reseten damit ich die mit dem CC2531 verbinden kann oder?

**Comment by hobbyquaker** [comment]
Jap.

**Comment by SkylightXD** [comment]
Hmm, klappt nicht... Hab alle Tastenkombination an zwei Hue Lampen durch, jeweils 10 Sekunden gedrückt gehalten. 

Ich kann die Fernbedienung auch nicht in RedMatic / Node Red anlernen... Aber die TRÅDFRI Produkte sollten funktionieren oder?

**Comment by SkylightXD** [comment]
Hab die Hue Lampe nun mit dem Hue Dimmer zurück gesetzt. Das hat geklappt :)
