### ISSUE TITLE
Get state of device

### ISSUE THREAD

**Issue by spiu16** [hobbyquaker/node-red-contrib-zigbee#32]
Hi,

any idea how I can get the state of a device (Osram Smart+ Plug)? I would like to use the tradfri remote (button "toggle") to turn the plug on or off. For that I need to retrieve the current state from the plug (ON/OFF) in order to send the appropriate message.

Thanks!

**Comment by dschido** [comment]
#20
keine Statusmeldung von Osram smart plug
Closed by dschido 8 days ago
bug to be clarified

**Comment by spiu16** [comment]
@dschido Danke, das issue hatte ich irgendwie überlesen. 
Ich bekomme auch den Status wenn das Gerät geschaltet wird (egal ob per Funk oder am Gerät selbst). Aber wie kann ich den aktuellen Status _vor_ dem Schalten abfragen (damit ich den richtigen Befehl (ON/OFF) senden kann, wenn ich per Taster (Toggle) schalten will)? 
Danke!

**Comment by SkylightXD** [comment]
Ich meine toggle als Attribut des Osram Plugs gesehen zu haben? Kannst du nicht dem smart plug den "Befehl" togglen schicken, so dass er das Umschalten übernimmt?

**Comment by spiu16** [comment]
Ah, super! so funktioniert es. Besten Dank!

**Comment by SkylightXD** [comment]
Gerne :) Zeig mal wie du das nun gelöst hast bzw. kannst du deinen Code posten?

**Comment by spiu16** [comment]
Am Ende ganz einfach. Dass es so einfach geht hätte ich nicht gedacht :)

`[{"id":"1e8eb4b2.cc5ebb","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"de3b2495.5a0958","type":"zigbee-converter","z":"1e8eb4b2.cc5ebb","shepherd":"9c891896.d6b5f8","name":"Remote2","topic":"zigbee/${ieeeAddr}","settopic":"zigbee/${ieeeAddr}/set","device":"0x90fd9ffffe6e01e3","attribute":"","payload":"json","x":80,"y":180,"wires":[["a72f091b.416c38"]]},{"id":"a72f091b.416c38","type":"zigbee-converter","z":"1e8eb4b2.cc5ebb","shepherd":"9c891896.d6b5f8","name":"Osram Plug1","topic":"zigbee/${ieeeAddr}","settopic":"zigbee/${ieeeAddr}/set","device":"0x7cb03eaa0a028c27","attribute":"","payload":"plain","x":650,"y":180,"wires":[[]]},{"id":"9c891896.d6b5f8","type":"zigbee-shepherd","z":"","name":"zigbee shepherd","path":"/dev/ttyACM0","baudRate":"115200","rtscts":true,"channelList":[11],"led":"disabled"}]`

![image](https://user-images.githubusercontent.com/45998371/57553735-b793ed80-736f-11e9-8fd3-df13dc3d0b48.png)

Remote2 ist dabei eine IKEA Tradfri Fernbedienung (E1524).
