### ISSUE TITLE
Need help for configuring node to control bulb

### ISSUE THREAD

**Issue by Baggerfahrer** [hobbyquaker/node-red-contrib-zigbee#33]
Hey all,

sorry for questioning this question, but i need help as i dont find the issue/ root cause for this error.
My flow looks like that, but unfortunaletyl, the bulb is not controlled...

![grafik](https://user-images.githubusercontent.com/25987294/57578894-84974a00-7494-11e9-8942-668f4cbf3b0a.png)

Precisely, i receive the following errors from the debug nodes:
`12.5.2019, 08:52:13node: zigbee shepherd
msg : string[20]
"Unrecognized command"`
`12.5.2019, 08:52:13node: 4d93410.405084zigbee/0x90fd9ffffe04bdb6/brightness : msg.payload : number
254`

The JSON node looks like that:
![grafik](https://user-images.githubusercontent.com/25987294/57578916-d9d35b80-7494-11e9-865e-61618398c78b.png)

The switch node is to filter the inputs of the WallSwitch. Its a two-sided button.

Can anyone help?
Would appreciate that! Many thanks!

**Comment by hobbyquaker** [comment]
I think you're misunderstanding purpose of the JSON node. It's not meant to set the payload, it's just a converter between JSON strings and Javascript objects (and vice versa). What you need instead is a _Change_ Node, configure it like that:

![image](https://user-images.githubusercontent.com/2503307/57585921-b1784b00-74ee-11e9-862f-05fce0e5a11a.png)

**Comment by Baggerfahrer** [comment]
Hey!

Many thanks for this answer!
As im now on a business trip for the Next 4 days, i can test it in the weekend. I will reply afterwards.

**Comment by Baggerfahrer** [comment]
works perfect! many thanks for that!
