### ISSUE TITLE
Hue Motion Sensor is not supported correctly?

### ISSUE THREAD

**Issue by Baggerfahrer** [hobbyquaker/node-red-contrib-zigbee#35]
Hi there!

It seems that the Hue Motion Sensor is not working properly?! 
I can pair this Sensor successfully and the zigbee shepherd reports it as correctly paired to the system.
![grafik](https://user-images.githubusercontent.com/25987294/57975764-31f7e980-79d0-11e9-80f0-bc4429e53c9b.png)

But the sensor is not reporting any data to the system at all. It can happen that the sensor reports data for some time, but at any time it stopps.

This is the log i get:

> 19.5.2019, 00:47:34node: zigbee shepherd
msg : string[88]
"configure failed 0x0017880104b5003b Bewegungsmelder Flur Error: Timed out after 10000 ms"

I can imagine that it is related to this topic here:
https://github.com/Koenkk/zigbee2mqtt/issues/893

But i am not able to delete/ unpair this sensor from the system, i always get the following error when pressing on the X next to device within node-red:

> 19.5.2019, 00:47:29node: zigbee shepherd
msg : string[57]
"remove 0x0017880104b5003b Error: Timed out after 10000 ms"

Anyone knows how to delete this device to repair?

**Comment by hobbyquaker** [comment]
Try it like Koenkk described here: https://github.com/Koenkk/zigbee2mqtt/issues/893#issuecomment-456034821
The shepherd database file is located in `~/.node-red/<node-id>/zigbee/dev.db`

**Comment by Baggerfahrer** [comment]
many thanks for the reply, and i wanted to try it accordingly, BUT:

i am not able to find the directory of the dev.db ...
i searched the entire folder structure of the rpi with WinSCP, either to the file dev.db or to the folder zigbee or the folder .node-red, but without success.

i installed node-red via the openhabiab-config tool.
any ideas where the files/ folders are located?

**Comment by hobbyquaker** [comment]
Node-RED logs the location of it's user dir on start:
`24 Feb 19:27:21 - [info] User directory : /root/.node-red`
and node-red-contrib-zigbee logs the location of the dev.db also:
`24 Feb 19:27:23 - [info] [zigbee-shepherd:shepherd] persistPath /root/.node-red/zigbee/f612aa9.2943d58`
So, if you can access the Node-RED log you should see where you can find the dev.db. If you can't even access the Node-RED log I can't help, then you should ask the openhabian-guys ;-)

**Comment by Baggerfahrer** [comment]
many thanks, i found the dev.db, it is located in the folder you said.
I processes the steps accordingly, but unfortunately without success. Here are the logs:

`20 May 20:32:41 - [error] [zigbee-shepherd:zigbee shepherd] configure failed 0x0017880104b5003b Phlips Hue Motion Sensor Error: Timed out after 10000 ms
20 May 20:34:23 - [warn] [zigbee-converter:Phlips Hue Motion Sensor] no converter available for 9290012607 genBasic readRsp
20 May 20:34:29 - [info] [zigbee-shepherd:zigbee shepherd] devInterview 0x0017880104b5003b
20 May 20:35:08 - [info] [zigbee-shepherd:zigbee shepherd] permitJoin 240 all
20 May 20:35:12 - [info] [zigbee-shepherd:zigbee shepherd] devInterview 0x0017880104b5003b
20 May 20:35:23 - [info] [zigbee-shepherd:zigbee shepherd] permitJoin 0 all
20 May 20:35:36 - [info] [zigbee-shepherd:zigbee shepherd] devInterview 0x0017880104b5003b`

Afterwards, i did a restart of node red, the the following logs showed up:

`20 May 20:35:54 - [info] [zigbee-shepherd:zigbee shepherd] devInterview 0x0017880104b5003b
20 May 20:35:54 - [info] [zigbee-shepherd:zigbee shepherd] devIncoming 0x0017880104b5003b
20 May 20:36:14 - [error] [zigbee-shepherd:zigbee shepherd] Cannot get the Node Descriptor of the Device: 0x0017880104b5003b (Error: Timed out after 10000 ms)
20 May 20:36:39 - [error] [zigbee-shepherd:zigbee shepherd] configure failed 0x0017880104b5003b  Error: Timed out after 10000 ms`

**Comment by Baggerfahrer** [comment]
no idea?

**Comment by hobbyquaker** [comment]
Should work with 0.9.x
