### ISSUE TITLE
RSSI / linkquality

### ISSUE THREAD

**Issue by hyteoo** [hobbyquaker/node-red-contrib-zigbee#37]
Hello

First of all, great job on porting all this to node-red
How can we access the device's RSSi or linkquality?
I tried the devices node output, event and converter outputs.

**Comment by hobbyquaker** [comment]
Until now you can use the Network Map feature to see the RSSI values (There is a link in the `Devices` Node Configuration)

**Comment by hyteoo** [comment]
Network map is awesome and does its job
However, that info is not available at any output of event / converter nodes, in order to use it in node red. 
Or am I missing something?

**Comment by hobbyquaker** [comment]
linkquality in msgs will be included in 0.9
