### ISSUE TITLE
advantages of this library

### ISSUE THREAD

**Issue by guitar9** [hobbyquaker/node-red-contrib-zigbee#38]
I currently control all my devices over mqtt and I am using zigbee2mqtt. Are there any advantages switching to this library?

**Comment by hobbyquaker** [comment]
If you're happy with zigbee2mqtt stick with it :)

Differences/Advantages of node-red-contrib-zigbee include:
* no MQTT Broker needed, convenient if you have everything in Node-RED anyways
* Converters are not mandatory - can be used with devices that have no converter (yet)
* mimics the hue api, easier to migrate from the hue bridge
