### ISSUE TITLE
Device Node - Wenn 0 injiziert wird 30 Sekunden Timer für Join?

### ISSUE THREAD

**Issue by Markus-** [hobbyquaker/node-red-contrib-zigbee#39]
Hallo,

ich hatte die Doku so verstanden, wenn ich 255 injiziere, dann ist das Joinen dauerhaft an - das läuft auch.
Wenn ich 0 injiziere, dann sollte das Joinen deaktiviert werden - allerdings läuft dann ein Timer 30 Sekunden runter und erst dann ist "Schluss".

Soll das so?

Gruß
Markus

**Comment by hobbyquaker** [comment]
Wird mit version 0.9 obsolet (anderes Handling von permitJoin)
