### ISSUE TITLE
Exemple Flow

### ISSUE THREAD

**Issue by joseluisgodinho** [hobbyquaker/node-red-contrib-zigbee#4]
Hello

Congrats for your hard work, would it be possible to had a small example flow?

**Comment by datobi2k** [comment]
Hi,
that's what I'm also interested in. I don't get commands to be send.

Unfortunately, I can't find any sample flow how to build it correct.

Maybe I'm a bit stupid, but I've got a CC2531 and 2 innr dim/adjustable white bulbs.
- installed git make build-essentials
- installed node-red-contrib-zigbee
- added device node
- added the shepherd (serial port was pre-configured and worked instantly, great!)
- detected and paired my 2 light-bulbs

Now I can see my paired devices in debug output from devices node, but I have no idea what to do in which format to get the the command node switching the bulbs on/off - or even more dim or change the white from warm to cold.

I'm expecting to set a payload with function on a button or switch to send this to the command node. But unlike the mqtt implementation, the command node has no configuration for the device to be controlled.

I have no idea how to setup the flow correct. Any ideas? hints?

**Comment by SkylightXD** [comment]
@joseluisgodinho 
Here are my config to connect the first devices:

![ZigBee_devices](https://user-images.githubusercontent.com/16561545/56213751-ea8ede00-605c-11e9-8395-a032067b54db.JPG)

![ZigBee_devices_config](https://user-images.githubusercontent.com/16561545/56213767-efec2880-605c-11e9-8fed-518b5bb90997.JPG)

![ZigBee_devices_shepherd_config](https://user-images.githubusercontent.com/16561545/56213770-f1b5ec00-605c-11e9-9e3e-f36c6a8e5f33.JPG)

**Comment by SkylightXD** [comment]
This is my way to switch the OSRAM smart+ plug:

![ZigBee_OSRAMplug](https://user-images.githubusercontent.com/16561545/56213856-1b6f1300-605d-11e9-99de-004c6a4c2e0a.JPG)

![ZigBee_OSRAMplug_1](https://user-images.githubusercontent.com/16561545/56213860-1f029a00-605d-11e9-86e6-bb80c10dd1c8.JPG)

This is the payload to power on:
`{"state":"on"}`

**Comment by joseluisgodinho** [comment]
Thank you

**Comment by gary-clarke** [comment]
I can pair a device and see messages in debug but when I press Deploy I loose device and no more messages. here are some debug messages before I hit Deploy.
08/10/2019, 17:40:24node: e2e7d625.f53848
zigbee/0x00158d0003496e82 : msg.payload : Object
{ click: "single", linkquality: 105 }
08/10/2019, 17:40:32node: e2e7d625.f53848
zigbee/0x00158d0003496e82 : msg.payload : Object
{ click: "double", linkquality: 94 }
08/10/2019, 17:40:34node: e2e7d625.f53848
zigbee/0x00158d0003496e82 : msg.payload : Object
{ click: "triple", linkquality: 94 }

Regards,
Gary

**Comment by marcsima79** [comment]
> 
> 
> I can pair a device and see messages in debug but when I press Deploy I loose device and no more messages. here are some debug messages before I hit Deploy.
> 08/10/2019, 17:40:24node: e2e7d625.f53848
> zigbee/0x00158d0003496e82 : msg.payload : Object
> { click: "single", linkquality: 105 }
> 08/10/2019, 17:40:32node: e2e7d625.f53848
> zigbee/0x00158d0003496e82 : msg.payload : Object
> { click: "double", linkquality: 94 }
> 08/10/2019, 17:40:34node: e2e7d625.f53848
> zigbee/0x00158d0003496e82 : msg.payload : Object
> { click: "triple", linkquality: 94 }
> 
> Regards,
> Gary
Hi,
I have the same Problem. Any solutions?
Best regards
