### ISSUE TITLE
devices Node - keine Devices aufgelistet - sonst läuft es

### ISSUE THREAD

**Issue by Markus-** [hobbyquaker/node-red-contrib-zigbee#40]
Hallo,

obwohl ich 5 Geräte verbinden konnte sehe ich in der Detail-Ansicht vom Device-Node keine Devices. Ganz am Anfang meine ich mich erinnern zu können, dass dort die ID + 2 Text-Felder pro Device waren - diese sind nicht mehr da - einfach ein leeres Feld mich keinerlei Text / Textfeldern.

Gruß
Markus

**Comment by Markus-** [comment]
Ich habe "zig" Mal den Flow redeployed, auch Node Red neu gestartet.

Irgendwann "ging" es...
Brauchst du bestimmte Infos?

Gruß
Markus

**Comment by hobbyquaker** [comment]
Check mal ob das in Version 0.9.0 jetzt passt. (Ich hab den Device Node rausgeworfen, die Device-Konfiguration ist jetzt im herdsman Node)
