### ISSUE TITLE
Hue Dimmer Switch gepaired aber keine Ausgabe

### ISSUE THREAD

**Issue by stuckis6er** [hobbyquaker/node-red-contrib-zigbee#41]
Hallo,
ich konnte den Switch pairen aber jetzt erhalte ich keine Ausgabe bei einem Tastendruck. Converter-node und Event-node getestet.
Ich habe den Switch auch schon mal removed und neu gepaired, das ändert leider nichts. Welche Möglichkeiten gibt es da noch?
Gruß Ralf

**Comment by thinkbig1979** [comment]
@stuckis6er 
I had a different issue, which was related to not being able to pair devices properly. I read a suggestion somewhere to unplug and re-plug the zigbee USB dongle and then reboot the host machine and restart zigbee2mqtt (or node-red in this case). That did solve my issue, worth a try perhaps.

**Comment by hobbyquaker** [comment]
In v0.8.1 the Hue Dimmer Switch should work as expected. Mind that it's needed that the Switch gets configured, the configuration is done automatically at the Start of node-red-contrib-zigbee. So you have to press some buttons then that the Switch awakes when starting, this has to be done only once. Look for `configure` debug log messages to see if it succeeded.

**Comment by stuckis6er** [comment]
Danke, jetzt funktioniert alles.
