### ISSUE TITLE
"Device with modelID 'Plug Z3' is not supported in v0.9.8"

### ISSUE THREAD

**Issue by Matten-Matten** [hobbyquaker/node-red-contrib-zigbee#42]
"Device with modelID 'Plug Z3' is not supported."

kANN ICH DAS IRGENDWIE TROTZDEM INTEGRIEREN?

**Comment by Matten-Matten** [comment]
Osram Smartplug!

**Comment by Hypnos3** [comment]
zum anlernen näher an den Router bringen und nochmal wiederholen.

Die Osram Teile sind manchmal etwas zickig beim anlernen. Ich hatte einen Zwischenstecker der hat auch eine Meldung ähnlich dieser gebracht.

**Comment by Matten-Matten** [comment]
"Device with modelID 'Plug Z3' is not supported."
"Please see: https://koenkk.github.io/zigbee2mqtt/how_tos/how_to_support_new_devices.html"
leider immer wieder diese Meldung.

Wie viele dieser Osram Plugs kann ich denn An ein CC2531 ZigBee USB-Stick anmelden?

**Comment by Matten-Matten** [comment]
bisher hab ich 6

**Comment by Matten-Matten** [comment]
"Cannot get the Node Descriptor of the Device: 0xf0d1b800001257f8 (Error: Timed out after 10000 ms)"

**Comment by Matten-Matten** [comment]
näher dran hab ich probiert, leider immer wieder ohne Erfolg.

**Comment by Hypnos3** [comment]
Der Router unterstützt normalerweise 25 Devices. Es gibt aber eine Firmware für die CC2531, welche erweitertes Routing, jedoch bedeutend weniger direkte devices unterstützt. 

Damit hängt das von der verwendeten Firmware ab. Schau mal bei Zigbee2mqtt Dokumentation.

**Comment by Matten-Matten** [comment]
ich hab das auch schon in betracht gezogen, dann muss ich mir wohl doch ein CC Debugger kaufen.
hatte folgenden fertig programmierten Stick bestellt:
https://www.amazon.de/gp/product/B07T3GM28F/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1

Kann man das irgendwie auslesen welche Firmware auf dem Stick ist?

**Comment by Matten-Matten** [comment]
Aug 14 22:43:48 ccu3-webui daemon.info node-red[25268]: [zigbee-shepherd:zigbee] coordinator 0x00124b0018e25e0a firmware version: 2.6.3 20190608

**Comment by Matten-Matten** [comment]
Ich kann machen was ich will ich bekomme die 4 neuen Osram Smartplugs nicht angelernt! Bitte um Hilfe, da ich diese sonst zurück schicke.

**Comment by Matten-Matten** [comment]
model: 'AC10691

**Comment by hobbyquaker** [comment]
`Device with modelID 'Plug Z3' is not supported`

Diese Meldung betrifft erstmal nur den Converter-Node, sollte kein Einfluss darauf haben ob sich ein Gerät pairen lässt oder nicht.

Ich hab bei den Osram Geräten die Erfahrung gemacht dass ich für das Pairen den Z-Stack resetten musste - und zwar für jedes Gerät erneut. 
Das lässt sich (noch) nicht über node-red-contrib-zigbee machen, der einfachste Weg ist: Node-RED stoppen, CC2531 aus- und wieder einstecken, Node-RED wieder starten, Pairing erlauben (am besten ohne Zeitlimit indem Du den Wert 255 in den Devices Node injectest), Gerät nah an den Stick bringen und Werksresetten (Knopf am Plug gedrückt halten bis klicken zu hören ist). Dann Geduld, kann durchaus sein dass die Meldung `Cannot get the Node Descriptor of the Device: xxxxx (Error: Timed out after 10000 ms)` ein paar mal erscheint es aber dann irgendwann doch klappt.

**Comment by Matten-Matten** [comment]
Ok, vielen dank hobbyquaker das funktioniert, scheint aber auch bekannt zu sein?

**Comment by hobbyquaker** [comment]
Bin mir nicht sicher wo da die Ursache liegt. Möglicherweise im Z-Stack (also der Firmware des Sticks) oder aber im znp/shepherd. Hab da aber auch nicht weiter geforscht, man muss die Geräte ja nur einmal pairen ;-)

**Comment by Matten-Matten** [comment]
ich musste aber folgendes in der device.js hinzufügen, damit sie funktionieren:

```
{
        zigbeeModel: ['Plug Z3'],
        model: 'AC10691',
        description: 'Smart+ plug',
        supports: 'on/off',
        vendor: 'LEDVANCE',
        fromZigbee: [fz.ignore_onoff_change, fz.state],
        toZigbee: [tz.on_off],
        configure: (ieeeAddr, shepherd, coordinator, callback) => {
            const device = shepherd.find(ieeeAddr, 3);
            const cfg = {direction: 0, attrId: 0, dataType: 16, minRepIntval: 0, maxRepIntval: 1000, repChange: 0};
            const actions = [
                (cb) => device.bind('genOnOff', coordinator, cb),
                (cb) => device.foundation('genOnOff', 'configReport', [cfg], foundationCfg, cb),
            ];

            execute(device, actions, callback);
        },
    },
```
++++++++++++++++++++
in der names.json tauchen die plugs dann so auf:

```
  "xxxxxxxxxxxx": {
    "name": "LEDVANCE Plug 4",
    "epDesc": [
      {
        "profId": 260,
        "epId": 1,
        "devId": 266,
        "inClusterList": [
          0,
          3,
          4,
          5,
          6,
          2821,
          4096,
          64527
        ],
        "outClusterList": [
          25
        ]
      },
      {
        "profId": 41440,
        "epId": 242,
        "devId": 97,
        "inClusterList": [],
        "outClusterList": [
          33
        ]
      }
    ],
    "type": "Router",
    "ieeeAddr": "xxxxxxxxxxxx",
    "nwkAddr": 4949,
    "manufId": 4489,
    "manufName": "LEDVANCE",
    "powerSource": "Mains (single phase)",
    "modelId": "Plug Z3",
    "epList": [
      1,
      242
    ],
    "status": "offline",
    "joinTime": null,
    "ts": 1566210550234
  }
```

**Comment by Matten-Matten** [comment]
ich muss auch dazu sagen das diese Geräte sehr oft keine Verbindung zum Stick haben.

**Comment by hobbyquaker** [comment]
> ich muss auch dazu sagen das diese Geräte sehr oft keine Verbindung zum Stick haben.

Die CC2531 sind leider funktechnisch nicht wirklich gut und die Osram Geräte dazu irgendwie recht "zickig". Ich würde da auf jeden Fall empfehlen einen Router mit CC2591 Verstärker und richtiger Antenne dazuzunehmen: https://www.zigbee2mqtt.io/how_tos/how_to_create_a_cc2530_router.html
Und/oder die Smart+ Plugs als zusätzliche Router, die gibts grade recht günstig: 
* https://www.amazon.de/Osram-schaltbare-fernbedienbar-Lichtsteuerung-kompatibel/dp/B074PZLX2P/ref=sr_1_5?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&keywords=smart%2B+plug&qid=1567802735&s=gateway&sr=8-5
* https://www.amazon.de/Osram-schaltbare-fernbedienbar-Lichtsteuerung-kompatibel/dp/B077VNL75Z/ref=sr_1_6?__mk_de_DE=%C3%85M%C3%85%C5%BD%C3%95%C3%91&keywords=smart%2B+plug&qid=1567802735&s=gateway&sr=8-6
Hab in meinem Netzwerk 2 CC2530+CC2591 Router und 2 Smart+ Plugs und es läuft nun (bis auf so ein Osram Outdoor Ding dass aber auch ziemlich weit weg ist) quasi 100% zuverlässig.

**Comment by hobbyquaker** [comment]
Ah und noch eine Anmerkung: im `hue light` Node gibt es seit v0.8.0 einen Retry bei nicht-erreichbarkeit, das hat bei mir die Probleme mit dem Osram Outdoor Ding umschifft. Gibts aber nur wenn Du den hue light node nutzt, der Converter Node macht kein Retry.

**Comment by Matten-Matten** [comment]
hab eben versucht die V0.8.0 zu aktualisieren, jedoch mit Fehler:
```
2868 verbose stack Error: @serialport/bindings@2.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
2868 verbose stack Exit status 1
2868 verbose stack     at EventEmitter.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
2868 verbose stack     at EventEmitter.emit (events.js:189:13)
2868 verbose stack     at ChildProcess.<anonymous> (/usr/local/addons/redmatic/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
2868 verbose stack     at ChildProcess.emit (events.js:189:13)
2868 verbose stack     at maybeClose (internal/child_process.js:970:16)
2868 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
2869 verbose pkgid @serialport/bindings@2.0.8
2870 verbose cwd /usr/local/addons/redmatic/var
2871 verbose Linux 4.19.71
2872 verbose argv "/usr/local/addons/redmatic/bin/node" "/usr/local/addons/redmatic/bin/npm" "install" "--no-package-lock" "--global-style" "--no-audit" "--no-update-notifier" "--save" "--save-prefix=\"~\"" "--production" "node-red-contrib-zigbee@0.8.0"
2873 verbose node v10.15.3
2874 verbose npm  v6.9.0
2875 error code ELIFECYCLE
2876 error errno 1
2877 error @serialport/bindings@2.0.8 install: `prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild`
2877 error Exit status 1
2878 error Failed at the @serialport/bindings@2.0.8 install script.
2878 error This is probably not a problem with npm. There is likely additional logging output above.
2879 verbose exit [ 1, true ]
```
was kann ich da tun?

Gruß
Matten

**Comment by hobbyquaker** [comment]
> hab eben versucht die V0.8.0 zu aktualisieren, jedoch mit Fehler:

Nutzt Du RedMatic? Falls ja - da lässt sich node-red-contrib-zigbee nicht über den Node-RED Palette Manager aktualisieren, da müsstest auf die aktuelle RedMatic Beta gehen oder noch Geduld haben bis ich die Finale 5.0 fertig hab.

**Comment by Matten-Matten** [comment]
Ja genau, Red Matic. OK kann ich eventuell das ganze auf die CCU kopieren?

**Comment by Matten-Matten** [comment]
```
		// LEDVANCE
	AC10691_cmdOn: {
        cluster: 'genOnOff',
        type: 'commandOn',
        convert: (model, msg, publish, options) => {
            return {action: 'up'};
        },
    },
    AC10691_cmdOff: {
        cluster: 'genOnOff',
        type: 'commandOff',
        convert: (model, msg, publish, options) => {
            return {action: 'down'};
        },
    },
	//
```

**Comment by Matten-Matten** [comment]
Moin, ich hab ein paar fragen bezüglich der Konfiguration und Bedienung.
Bei mir taucht folgender Fehler auf.
`configure failed 0xf0d1b80000125523 (LEDVANCE Plug 1) Cannot read property 'bind' of undefined`

was ist dieses 'bind' und was konfiguriere ich dort genau? Ich stehe da irgendwie aufm schlauch. 
![Node-RED _ bind](https://user-images.githubusercontent.com/32074970/66471677-0adbaa80-ea8c-11e9-9746-063aaca318d8.png)

Kannst du mir das erläutern? Danke im voraus.

Gruß
Matten Matten
