### ISSUE TITLE
How to keep up to date with the zigbeetomqtt updates

### ISSUE THREAD

**Issue by thinkbig1979** [hobbyquaker/node-red-contrib-zigbee#43]
Is there an easy way to make sure the library is more or less up to date with the developments on koenkk's side (converters and devices). I thought perhaps to update the dependencies  in the package.json and run `npm install` again, but I don't know if that's smart :-)

`  
"zigbee-shepherd": "git+https://github.com/Koenkk/zigbee-shepherd.git#a8b5828200140adf4de83457508576f6879f7ec1",
"zigbee-shepherd-converters": "8.1.4"
`

**Comment by hobbyquaker** [comment]
you could do this, as long as there are no breaking changes in the converters this _should_ work. Otherwise just be patient until a version of node-red-contrib-zigbee is released.

**Comment by thinkbig1979** [comment]
Understood. Thanks for the response.
