### ISSUE TITLE
Errors running version 0.8.0

### ISSUE THREAD

**Issue by hyteoo** [hobbyquaker/node-red-contrib-zigbee#45]
Upgraded to latest version 0.8.0
I now get many timeout errors on the zigbee nodes.
1/2 times a node red restart fixes it. the rest 1/2 times - 2 node red restarts fixes it

Every deployment also causes a timeout on the nodes.

Here's my scenario now

1. Deploy
2. Zigbee nodes switch to Closing state
![zig1](https://user-images.githubusercontent.com/1378206/64485715-81d31880-d22c-11e9-8906-d380cba612e9.PNG)
3. After deployment:
![zig2](https://user-images.githubusercontent.com/1378206/64485721-93b4bb80-d22c-11e9-9207-20994f99cd94.PNG)

Also in debug:
![zig12](https://user-images.githubusercontent.com/1378206/64485722-9a433300-d22c-11e9-8767-d8288bc485f9.PNG)

**Comment by hyteoo** [comment]
Some more updates here:
I run a Ubuntu Server 18.04, with latest updates applied, on a NUC i5 gen8.
The CC2531 stick is the only USB device plugged in
It has worked perfectly for the past ~3 months.

- I reflashed the CC2531 again with the latest firmware, same behavior
- I tried hitting the reset button, no luck
- ModemManger is not installed
- All user rights are unchanged.

I read through the issues on Koenkk's github but no solution could be found.
I also tried to manually update the files from his repos, but the nodes stop working altogether then :(

Any ideas on what could have caused this?

**Comment by Baggerfahrer** [comment]
exactly the same issue here. same behaviour, restart of node-red helps to get it working again....

**Comment by hobbyquaker** [comment]
I'm currently working on the migration from zigbee-shepherd to zigbee-herdsman, so I won't investigate on this bug and have to ask you for patience until I can release the 0.9 version

**Comment by hyteoo** [comment]
That would be the best. I setup zigbee2mqtt on a Pi and it seems there are problems with the main branch.

Checked out the dev branch and all works OK.

So I think this comes from zigbee2mqtt.
I would say close this issue and recreate if problem persists after 0.9

Good job so far Sebastian! Really appreciate your work.
