### ISSUE TITLE
"TypeError: Cannot read property 'disFeedbackRsp' of undefined"

### ISSUE THREAD

**Issue by Baggerfahrer** [hobbyquaker/node-red-contrib-zigbee#46]
Hi there,

since today, a new failure arrised. I updated to the newest version of node-red-contrib-zigbee (version 0.8.0) and did a full update of the rpi.

Since yesterday, communication to all my zigbee actors worked perfectly, but today, no actions are set anymore.

Log Entry of Node-Red:
![grafik](https://user-images.githubusercontent.com/25987294/64917734-bf3b2700-d793-11e9-99b2-3eb4794ca2b0.png)

The bulbs i want to set are IKEA tradfri bulbs, maybe that helps.

Many thanks!

**Comment by hobbyquaker** [comment]
I'm currently working on the migration from zigbee-shepherd to zigbee-herdsman, so I won't investigate on this bug and have to ask you for patience until I can release the 0.9 version

**Comment by Baggerfahrer** [comment]
> 
> 
> I'm currently working on the migration from zigbee-shepherd to zigbee-herdsman, so I won't investigate on this bug and have to ask you for patience until I can release the 0.9 version

Many thanks for the answer!
Thats quite fine for me, could you give me an time frame/ schedule when you plan to have the migration finished? I woud like to have a rough overview and time line ....

**Comment by hobbyquaker** [comment]
I plan to release 0.9 on the last september weekend.
