### ISSUE TITLE
Control of Trafdri Bulbs - Issue related to new version 0.8.0 or syntax error?

### ISSUE THREAD

**Issue by Baggerfahrer** [hobbyquaker/node-red-contrib-zigbee#48]
Hi all,

concerning this issue here [https://github.com/hobbyquaker/node-red-contrib-zigbee/issues/46#issue-493701926](url) i am wondering of i did something wrong to adress my tradfri bulbs or if someone else experience atm the same issue. 

Can we compare the payload we send to the bulbs, just to verify that i did not have done any mistaktes in the syntax or something else?

E.g. one example of a flow is as follows:
![grafik](https://user-images.githubusercontent.com/25987294/64982406-6ddb8680-d8be-11e9-9163-df32cf01c316.png)

> [{"id":"793cc81.0892e38","type":"zigbee-converter","z":"9e4c8be8.7454f8","shepherd":"9a81a4dd.f9bc5","name":"Lampe Flur","topic":"zigbee/${ieeeAddr}","settopic":"zigbee/${ieeeAddr}/set","device":"0x90fd9ffffe04bdb6","attribute":"","payload":"plain","x":1570,"y":120,"wires":[[]]},{"id":"9a81a4dd.f9bc5","type":"zigbee-shepherd","z":"","name":"zigbee shepherd","path":"/dev/ttyUSB-zigbee2mqtt","baudRate":"115200","rtscts":true,"channelList":[18],"led":"enabled"}]

Meaning my payload is:
![grafik](https://user-images.githubusercontent.com/25987294/64982520-ab401400-d8be-11e9-96e6-051a6fc5f6ea.png)

What do you have?
Many thanks!

**Comment by hobbyquaker** [comment]
I'm not using the "converter" node but the "hue light" node to control my bulbs, but I would say your payload looks correct.
