### ISSUE TITLE
Livolo zigbee switches 

### ISSUE THREAD

**Issue by Giaitzoglou** [hobbyquaker/node-red-contrib-zigbee#5]
Hi can you please tell if the Livolo zigbee switches are compatible? 
Thanks ina advance
Chris

**Comment by hobbyquaker** [comment]
As I'm using Koenkk's fork of the [zigbee-shepherd](https://github.com/Koenkk/zigbee-shepherd) and his [zigbee-shepherd-converters](https://github.com/Koenkk/zigbee-shepherd-converters) for the converter node the answer is simple: everything that is supported by [zigbee2mqtt](https://www.zigbee2mqtt.io/) should also work in node-red-contrib-zigbee.
