### ISSUE TITLE
TypeError: Cannot read property 'joinPermitted' of undefined

### ISSUE THREAD

**Issue by miDan23** [hobbyquaker/node-red-contrib-zigbee#50]
After installing Node-Red, node-red-dashboard and node-red-contrig-zigbee I just started Node Red and found this in the systemd journal (The messages are coming every second):

Sep 29 15:37:14 miranda red.js[6417]: TypeError: Cannot read property 'joinPermitted' of undefined
Sep 29 15:37:14 miranda red.js[6417]:     at RED.httpAdmin.get (........./node_modules/node-red-contrib-zigbee/nodes/shepherd.js:33:58)
Sep 29 15:37:14 miranda red.js[6417]:     at Layer.handle [as handle_request] (........./node_modules/express/lib/router/layer.js:95:5)
Sep 29 15:37:14 miranda red.js[6417]:     at next (........./node_modules/express/lib/router/route.js:137:13)
Sep 29 15:37:14 miranda red.js[6417]:     at Route.dispatch (........./node_modules/express/lib/router/route.js:112:3)
Sep 29 15:37:14 miranda red.js[6417]:     at Layer.handle [as handle_request] (........./node_modules/express/lib/router/layer.js:95:5)
Sep 29 15:37:14 miranda red.js[6417]:     at ........./node_modules/express/lib/router/index.js:281:22
Sep 29 15:37:14 miranda red.js[6417]:     at Function.process_params (........./node_modules/express/lib/router/index.js:335:12)
Sep 29 15:37:14 miranda red.js[6417]:     at next (........./node_modules/express/lib/router/index.js:275:10)
Sep 29 15:37:14 miranda red.js[6417]:     at expressInit (........./node_modules/express/lib/middleware/init.js:40:5)
Sep 29 15:37:14 miranda red.js[6417]:     at Layer.handle [as handle_request] (........./node_modules/express/lib/router/layer.js:95:5)

**Comment by hobbyquaker** [comment]
Should be fixed in 0.9.6

**Comment by miDan23** [comment]
It is!

Thank you!
