### ISSUE TITLE
Cannot read property '...' of undefined

### ISSUE THREAD

**Issue by miDan23** [hobbyquaker/node-red-contrib-zigbee#51]
With just a controller node with 9 zigbee devices configured (4 lamps, 4 motion sensors and one dimmer switch):
Each time I deploy, I get the error "Cannot read property '...' of undefined". Between the two ' is the ieeeAddr of the first device (second device, if the first is the coordinator).

**Comment by hobbyquaker** [comment]
can you pls provide a Node-RED log on debug level (see https://nodered.org/docs/user-guide/runtime/logging) with a few lines around that exception?

**Comment by miDan23** [comment]
No Problem:

Sep 29 20:09:24 miranda red.js[6932]: 29 Sep 20:09:24 - [info] Started flows
Sep 29 20:09:24 miranda red.js[6932]: 29 Sep 20:09:24 - [info] Server now running at http://127.0.0.1:1880/
Sep 29 20:09:25 miranda red.js[6932]: 29 Sep 20:09:25 - [debug] [zigbee-shepherd:zigbee herdsman] add deviceAnnounce listener
Sep 29 20:09:25 miranda red.js[6932]: 29 Sep 20:09:25 - [debug] [zigbee-shepherd:zigbee herdsman] add deviceLeave listener
Sep 29 20:09:25 miranda red.js[6932]: 29 Sep 20:09:25 - [debug] [zigbee-shepherd:zigbee herdsman] add adapterDisconnected listener
Sep 29 20:09:25 miranda red.js[6932]: 29 Sep 20:09:25 - [debug] [zigbee-shepherd:zigbee herdsman] add deviceJoined listener
Sep 29 20:09:25 miranda red.js[6932]: 29 Sep 20:09:25 - [debug] [zigbee-shepherd:zigbee herdsman] add deviceInterview listener
Sep 29 20:09:25 miranda red.js[6932]: 29 Sep 20:09:25 - [debug] [zigbee-shepherd:zigbee herdsman] add message listener
Sep 29 20:09:25 miranda red.js[6932]: 29 Sep 20:09:25 - [info] [zigbee-shepherd:zigbee herdsman] Currently 9 devices are joined:
Sep 29 20:09:25 miranda red.js[6932]: 29 Sep 20:09:25 - [info] [zigbee-shepherd:zigbee herdsman] {ieeeAddr} lFlur (Router Philips LCT015)
Sep 29 20:09:25 miranda red.js[6932]: 29 Sep 20:09:25 - [error] [zigbee-shepherd:zigbee herdsman] Cannot read property '{ieeeAddr}' of undefined
Sep 29 20:09:25 miranda red.js[6932]: 29 Sep 20:09:25 - [info] [zigbee-shepherd:zigbee herdsman] Zigbee network parameters: {"panID":59838,"extendedPanID":"0xdddddddddddddddd","channel":11}
Sep 29 20:09:25 miranda red.js[6932]: 29 Sep 20:09:25 - [info] [zigbee-shepherd:zigbee herdsman] Coordinator: zStack12 2.6.3 20190425
Sep 29 20:10:09 miranda red.js[6932]: 29 Sep 20:10:09 - [debug] [zigbee-shepherd:zigbee herdsman] message attributeReport ...
Sep 29 20:10:09 miranda red.js[6932]: 29 Sep 20:10:09 - [debug] [zigbee-shepherd:zigbee herdsman] configure ...
Sep 29 20:10:14 miranda red.js[6932]: 29 Sep 20:10:14 - [info] [zigbee-shepherd:zigbee herdsman] successfully configured ...

**Comment by hobbyquaker** [comment]
should be fixed with v0.9.7

**Comment by miDan23** [comment]
The Error ist gone...

But several seconds after a deploy, I get these two messages:

Sep 29 21:41:32 miranda red.js[7065]: 29 Sep 21:41:32 - [error] [zigbee-shepherd:zigbee herdsman] configure failed 0x......... (dimmer switch) AREQ - ZDO - bindRsp after 10000ms
Sep 29 21:41:32 miranda red.js[7065]: 29 Sep 21:41:32 - [error] [zigbee-shepherd:zigbee herdsman] configure failed 0x......... (motion sensor) AREQ - ZDO - bindRsp after 10000ms

Doesn't seem to be serious, because an event node (set up with the dimmer switch) connected to a debug node sends messages ...

**Comment by hobbyquaker** [comment]
These messages can be safely ignored. Will reduce the severity to `warn`. node-red-contrib-zigbee will try to configure these devices again as soon as they contact the coordinator.
