### ISSUE TITLE
ZigBee Network Map wird nicht angezeigt

### ISSUE THREAD

**Issue by Ixuser-1** [hobbyquaker/node-red-contrib-zigbee#54]
Bis Version 0.7.2 habe ich mit in der device node die Graphviz-Daten generieren lassen. Mit Version 0.9.2 bekomme ich die folgende Fehlermeldung, wenn ich in der herdsman mode auf Network Map klicke:
`ZigBee Network Map
JSON.parse: unexpected character at line 1 column 1 of the JSON data`

In welcher Datei müsste der Fehler sein? Dann kann ich diese hier anhängen.

**Comment by hyteoo** [comment]
I have a similar problem, different message however:

**ZigBee Network Map**
Unexpected token U in JSON at position 0

**Comment by Ixuser-1** [comment]
When i use Chrome (Android) i get the same message like hyteoo and with Firefox (also Android) the message i posted first.

**Comment by hyteoo** [comment]
Some more details related to this:
![nodered zigbee error](https://user-images.githubusercontent.com/1378206/66625715-18b13d00-ebfe-11e9-9c52-fe7a425b5fe3.PNG)

Seems the script looks for the /devices path which does not exist.
Google Chrome Windows 10, version 77.0.3865.90 (Official Build) (64-bit)

**Comment by Ixuser-1** [comment]
It seems we both access node-red from a different subnet. I access node-red over two via VPN (Fritzbox) coupled subnets. And since hyteoo hides his domain in the screenshot, I suspect that it is a public domain and he accesses node-red over the Internet.

**Comment by Ixuser-1** [comment]
It seems we both access node-red from a different subnet. I access node-red over two via VPN (Fritzbox) coupled subnets. And since hyteoo hides his domain in the screenshot, I suspect that it is a public domain and he accesses node-red over the Internet.

A few more details, I use Redmatic 5.0 with authentication for admin and node with username / password individually.

**Comment by hobbyquaker** [comment]
Sollte mit node-red-contrib-zigbee 0.11.0 bzw. RedMatic 5.0.1 gefixt sein.

**Comment by Ixuser-1** [comment]
Thank you! The network map works fine now!
