### ISSUE TITLE
Neue Fimware für 0.12.2 erfoderlich ?

### ISSUE THREAD

**Issue by chris8519** [hobbyquaker/node-red-contrib-zigbee#57]
Hey habe nach den ganzen updates der letzten tage immer den fehler 
SRSP - SYS - version after 6000ms
 und diverse andere anscheinend klappt die verbindung nicht so recht 
Welche firmware ist für die aktuelle version für den CC2531 erforderlich

mfg

**Comment by hobbyquaker** [comment]
Ich nutze schon seit mehreren Monaten diese hier:
`2|node-red  | 13 Oct 17:43:34 - [info] [zigbee-shepherd:herdsman] Coordinator: zStack12 2.6.3 20190608`

An sich sollten aber alle Firmwares die Koenkk anbietet funktionieren: https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator

**Comment by chris8519** [comment]
Habe node red zigbee deinstalliert und einen anderen cc2531 mit 2.6.3 20190608 Firmware benutzt dann ging es wieder ... jetzt mit /dev/ttyACM0 und vorher war der andere stick mit /dev/serial/by-id angebunden (Nodered läuft über iobroker auf einem Raspberry4) .... falls es wieder Probleme geben sollte werde ich mich melden
