### ISSUE TITLE
group management seems to be broken

### ISSUE THREAD

**Issue by renkei** [hobbyquaker/node-red-contrib-zigbee#60]
Hi hobbyquaker,

thanks for the great work! I'm using this package with RedMatic on RaspberryMatic (Raspberry Pi 3 + RPI-RF-MOD + CC2531 Zigbee USB Stick). I'm able to control my hue devices with RedMatic. But when I try to group some bulbs then it doesn't work. Steps to reproduce:

1. Open properties dialog of the zigbee herdsman node
2. Go to tab "Groups"
3. Press the "+ add group" button
4. In the new dialog, enter an ID (e.g. 1) and a group name, close dialog by pressing "Add Group"
5. Select the created group and press the "+ add member" button
6. In the new dialog, select an available zigbee device. What about the second combo box with numbers? I can select 11 and 242, what is it about, what do I have to select? I've tested both, when I try to close the dialog by pressing the "Add member" button I get an error message box with "unknown group undefined".
7. Ok, this doesn't work, the group is still empty, so I want to remove the empty group now by pressing the "x" button. This results in an error message box with "removeGroup group 1 not empty"
8. How to get rid of this group now? I'm not able to reset the groups stuff.

RenKei

**Comment by hobbyquaker** [comment]
@renkei should be fixed with 0.14.2

**Comment by kneip68** [comment]
Works for me.

**Comment by renkei** [comment]
Updated from RedMatic 5.1.2 to 5.2.0 and node-red-contrib-zigbee 0.14.0 to 0.15.0 and now it works for me as well. Thanks a lot.
