### ISSUE TITLE
Question about hue

### ISSUE THREAD

**Issue by erikvg01** [hobbyquaker/node-red-contrib-zigbee#61]
Would it be possible to see some basic syntax for how the JSON object should be formatted before sent to the HUE node?  I know documentation is further down the dev list, but I would love to start playing with it.

**Comment by hobbyquaker** [comment]
It has the same json schema like the philips hue bridge api. So you can send msgs like e.g. `{"topic":"hue/set/lights/<deviceName>", "payload": {"on":true, "bri":254, "ct":350}}` or you can use plain payload if you append the property: `{"topic":"hue/set/lights/<deviceName>/bri", "payload":254}`
To control Groups just replace "lights" by "groups" in topic.

**Comment by erikvg01** [comment]
Thank you.  This doesn't seem to be working and I'm getting no errors back.  Does the HUE node require configuration, or should the default values accept variables from preceding nodes?

**Comment by hobbyquaker** [comment]
defaults should be fine. To see what's going wrong you need to raise log level of Node-RED to debug.

**Comment by erikvg01** [comment]
Thank you.  When sending data to the hue node, I get:  topic mismatch  hue/set/${type}/${name}/${attribute}

Exact input was:

{
    "topic":"hue/set/lights/3",
    "payload": 
        {
            "on":false,
            "bri":254, 
            "ct":350
        }

}

**Comment by erikvg01** [comment]
After adjusting how I was building the input, I am now getting:    TypeError: Cannot read property 'find' of undefined

Previously I was incorrectly defining msg.topic.

**Comment by hobbyquaker** [comment]
you have to either change the topic configuration to `hue/set/${type}/${id}/${attribute}` or you have to change the topic to publish to `hue/set/lights/<device name>` (replace <device name> by the name of the device configured in the devices tab)

**Comment by erikvg01** [comment]
Wonderful.  I have control over my light bulbs now!  The issue now appears that "on": false   does not result in shutting the bulb off.  It seems you must set brightness to 0 for it to turn off.  Thank you so much for prompt responses!

**Comment by hobbyquaker** [comment]
hmm... that _should_ work with `"on":false`. Will have to investigate if there is a bug.

**Comment by hobbyquaker** [comment]
Can confirm this is a bug: #63

**Comment by erikvg01** [comment]
I apologize, but the HUE configuration is somewhat mystifying.  What is the purpose/difference of "topic" and "set topic"?

**Comment by hobbyquaker** [comment]
`topic` configures the topic of messages send on the node output. `set topic` and `get topic` configure topics of messages that arrive on the node input.

**Comment by erikvg01** [comment]
That helps clarify.  Thank you very much!

**Comment by hobbyquaker** [comment]
will close here, the `"on": false` issue continues here: #63
