### ISSUE TITLE
Command Node works with "Execute Command" Button but not with incoming msg

### ISSUE THREAD

**Issue by hobbyquaker** [hobbyquaker/node-red-contrib-zigbee#62]

**Comment by hobbyquaker** [comment]
@kneip68 should be fixed with v0.14.2

**Comment by kneip68** [comment]
Just installed 0.15 will check tomorrow

**Comment by kneip68** [comment]
Works now:
![image](https://user-images.githubusercontent.com/44921902/67483283-c6dcce00-f665-11e9-8b3e-e86ce51120b0.png)
