### ISSUE TITLE
hue node: payload {"on":false} doesnt switch off a bulb

### ISSUE THREAD

**Issue by hobbyquaker** [hobbyquaker/node-red-contrib-zigbee#63]

**Comment by hobbyquaker** [comment]
@ericvg01 - is the bulb configured to do reporting (in DevConfig tab)? Could you show me a log (set Node-REDs log level to debug)?

**Comment by erikvg01** [comment]
Reporting appears not to be working.

0|node-red | 22 Oct 16:32:18 - [warn] [zigbee-shepherd:zigbee herdsman] reporting setup 0x<truncate> 3 - already configuring
0|node-red | 22 Oct 16:32:18 - [info] [zigbee-shepherd:zigbee herdsman] Zigbee network parameters: {"panID":55994,"extendedPanID":"0xdddddddddddddddd","channel":25}
0|node-red | 22 Oct 16:32:18 - [info] [zigbee-shepherd:zigbee herdsman] Coordinator: zStack12 2.6.3 20190608
0|node-red | 22 Oct 16:32:20 - [error] [zigbee-shepherd:zigbee herdsman] Failed to setup reporting for 0x<truncate> 3 - Timeout - 17848 - 11 - 226 - 7 after 10000ms

**Comment by hobbyquaker** [comment]
I guess than the root cause is is that the bulb gets blocked by the failing try to setup reporting. Just try to uncheck that for this bulb and check if you can turn it off with payload `{"on":false}` then.

**Comment by erikvg01** [comment]
Having reporting turned on in DevConfig has no impact on this behavior.  "on": false    does not turn the bulbs off.

**Comment by hobbyquaker** [comment]
hmm... can you pls set your node-red to log level debug and show me?

**Comment by erikvg01** [comment]
Yes...  I mis-configured something and now cannot control the lights.  Once I have this corrected I will send along the requested debug.

**Comment by erikvg01** [comment]
All event logging below resulted in the light being turned ON.  I have 2 bulbs exhibiting the same behavior, this is logging for a single bulb.

0|node-red | 22 Oct 21:34:15 - [debug] [zigbee-hue-light:8859a2ca.ab3868] putLightState 0x<tct> 2 {"on":"true","bri":"254","ct":"350","transitiontime":0}
0|node-red | 22 Oct 21:34:15 - [debug] [zigbee-shepherd:zigbee herdsman] command successful 0x<tct> 2 11 genLevelCtrl moveToLevelWithOnOff {"level":"254","transtime":0}
0|node-red | 22 Oct 21:34:15 - [debug] [zigbee-shepherd:zigbee herdsman] reporting setup 0x<tct> 2
0|node-red | 22 Oct 21:34:15 - [info] [zigbee-shepherd:zigbee herdsman] bind 0x<tct> 11 genOnOff to coordinator
0|node-red | 22 Oct 21:34:15 - [debug] [zigbee-shepherd:zigbee herdsman] command successful 0x<tct> 2 11 lightingColorCtrl moveToColorTemp {"colortemp":"350","transtime":0}
0|node-red | 22 Oct 21:34:15 - [warn] [zigbee-shepherd:zigbee herdsman] reporting setup 0x<tct> 2 - already configuring
0|node-red | 22 Oct 21:34:15 - [info] [zigbee-shepherd:zigbee herdsman] bind 0x<tct> 2 11 genOnOff to 0x00124b00193b074a Coordinator 1 successful
0|node-red | 22 Oct 21:34:15 - [info] [zigbee-shepherd:zigbee herdsman] configureReporting 0x<tct> 2 genOnOff [{"attribute":"onOff","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":0}]

0|node-red | 22 Oct 21:34:21 - [debug] [zigbee-hue-light:8859a2ca.ab3868] putLightState 0x<tct> 2 {"on":"false","bri":"254","ct":"350","transitiontime":0}
0|node-red | 22 Oct 21:34:25 - [error] [zigbee-shepherd:zigbee herdsman] Failed to setup reporting for 0x<tct> 2 - Timeout - 40960 - 11 - 66 - 7 after 10000ms
0|node-red | 22 Oct 21:34:25 - [debug] [zigbee-shepherd:zigbee herdsman] command successful 0x<tct> 2 11 genLevelCtrl moveToLevelWithOnOff {"level":"254","transtime":0}
0|node-red | 22 Oct 21:34:25 - [debug] [zigbee-shepherd:zigbee herdsman] reporting setup 0x<tct> 2
0|node-red | 22 Oct 21:34:25 - [info] [zigbee-shepherd:zigbee herdsman] bind 0x<tct> 11 genOnOff to coordinator
0|node-red | 22 Oct 21:34:26 - [debug] [zigbee-shepherd:zigbee herdsman] command successful 0x<tct> 2 11 lightingColorCtrl moveToColorTemp {"colortemp":"350","transtime":0}
0|node-red | 22 Oct 21:34:26 - [warn] [zigbee-shepherd:zigbee herdsman] reporting setup 0x<tct> 2 - already configuring
0|node-red | 22 Oct 21:34:26 - [info] [zigbee-shepherd:zigbee herdsman] bind 0x<tct> 2 11 genOnOff to 0x00124b00193b074a Coordinator 1 successful
0|node-red | 22 Oct 21:34:26 - [info] [zigbee-shepherd:zigbee herdsman] configureReporting 0x<tct> 2 genOnOff [{"attribute":"onOff","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":0}]

**Comment by hobbyquaker** [comment]
Got it. That is a result of using the "moveToLevelWithOnOff" Command, that switches the lamp on if bri is > 0. Have to rethink that, give me some time.

**Comment by hobbyquaker** [comment]
@erikvg01 that seems to be not so trivial as I was hoping ;-) Will have to think about that and re-check Hue API behavior (because the "hue" nodes concept is to behave like the Hue bridge API). For now you can workaround that by just omitting the `bri` property. Will check to you as soon as I have a better solution.
