### ISSUE TITLE
Devices disappearing after deploy

### ISSUE THREAD

**Issue by marcsima79** [hobbyquaker/node-red-contrib-zigbee#66]
Hi,

If I deploy the flow all devices disappears from herdsman.
I have to join the devices again.

node-red-contrib-zigbee
0.15.0

Best regards

**Comment by fbeek** [comment]
Hello,

i have the same problem, have you any solutions for this problem?

Best Regards

**Comment by hobbyquaker** [comment]
@fbeek @marcsima79 are you using Z-Stack 1.2 or 3.x on your coordinator? I'm chasing some bug with invalid panIDs that lead to database deletion with Z-Stack 3.x, so if you're on 3.x I suggest you try to set a new panId. To check what's happening it would be also useful to generate some herdsman debug log by starting Node-RED like this: `DEBUG=zigbee-herdsman:adapter:zStack:startZnp node-red`. Also set log level of Node-RED to debug pls.

**Comment by Sineos** [comment]
I had the same issue. I deleted the dev.db and its backup under /usr/local/addons/redmatic/var/zigbee/, changed panID and Network Key and this seems to have fixed it.

Running Z-Stack 3.x

**Comment by fbeek** [comment]
Hello,

iam using Stack Version 1.2.
I tried deleting the DB and changing the network and PanID but it chnages nothing.

I will send you the debug output at the weekend. I need to change my docker container for that.

THX for your help!

**Comment by fbeek** [comment]
I found a solution for me. I checked the on firat start per default generated NetworkKey length and it was so long. 

I changed it to a 32 character long HexString and restarted everything and now it works.

I think this is the problem, can somebody confirm this?

Regards

**Comment by hobbyquaker** [comment]
default should be `01030507090B0D0F00020406080A0C0D`. Did yours differ from that?

**Comment by marcsima79** [comment]
> 
> 
> default should be `01030507090B0D0F00020406080A0C0D`. Did yours differ from that?
if i create a new herdsman, yes this is the default "01030507090B0D0F00020406080A0C0D"
I dont know why, but i had a 64-CharacterHexString as Networkkey
@fbeek thanks for the info

**Comment by hobbyquaker** [comment]
@marcsima79 so is it working for you now?

**Comment by marcsima79** [comment]
Hi,
Yes with the shorter 32bit key it works fine.
Thanks

Am 18. November 2019 18:16:14 MEZ schrieb Sebastian Raff <notifications@github.com>:
