### ISSUE TITLE
[Question] Z-Stack 3

### ISSUE THREAD

**Issue by Sineos** [hobbyquaker/node-red-contrib-zigbee#67]
Will node-red-contrib-zigbee work with Z-Stack 3 and LAUNCHXL-CC1352P-2 (ref https://github.com/Koenkk/zigbee2mqtt/issues/1429)?

**Comment by Koenkk** [comment]
node-red-contrib-zigbee and zigbee2mqtt share the same zigbee library (zigbee-herdsman), so probably yes.

**Comment by hobbyquaker** [comment]
I'm using a 2652 with Koenkks Z-Stack 3.x.0 for a test system and it works. Had some issues that herdsman cleared the database cause of an invalid panID, but since I changed the default panID it seems to be stable. (https://github.com/hobbyquaker/node-red-contrib-zigbee/issues/66)

**Comment by Sineos** [comment]
Exactly the same experience here
