### ISSUE TITLE
Deconz (Conbee) support?

### ISSUE THREAD

**Issue by bohtho** [hobbyquaker/node-red-contrib-zigbee#68]
I understand zigbee-herdsman has started support for other zigbee hardware like CC2652R1 and Conbee. Will they also work in node-zigbee? I have a Conbee and wish to switch away from Deconz REST API.

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Sineos** [comment]
CC2652R1 and CC1352P are working. Conbee does not, since not yet implemented in the herdsman framework. Work to support the Conbee has started but not yet available. Ref https://github.com/Koenkk/zigbee-herdsman/issues/72

**Comment by hobbyquaker** [comment]
as soon as the herdsman supports it it will be supported in node-red-contrib-zigbee also.
