### ISSUE TITLE
A suggestion on attribute reports

### ISSUE THREAD

**Issue by alpintrekker** [hobbyquaker/node-red-contrib-zigbee#7]
Hi, hobbyquaker,

what a promising work! 
As it is in a 'work-in-progress' status I'd suggest a minor change, so the topic of the attReport event message to reflect full ZigBee characteristics, like this:

ieeeAddr / attReport / endPoint / clusterId / attributeId

since now it is impossible to determine, which endpoint of my dual switch the report came from since the 'device' property of the message object holds the whole epList, not the source endpoint.

With complex devices, a good number of clusters with dozens of attributes could appear, so that's why I suggest the topic structure above.
 
Regards,
András

**Comment by hobbyquaker** [comment]
I plan to make the topic configurable utilizing placeholders, so you could then e.g. use `${ieeeAddr}/attReport/${ep}/${cid}/${attribute}`.

**Comment by alpintrekker** [comment]
Looking forward to that!
