### ISSUE TITLE
Geräte verschwinden von allein

### ISSUE THREAD

**Issue by Matten-Matten** [hobbyquaker/node-red-contrib-zigbee#75]
Hallo @hobbyquaker,
Ich habe leider seit einiger Zeit das urplötzlich alle angelernten  Geräte aus dem zigbee Controller verschwinden. Die device.db ist dann auch leer lediglich der zstack ist dann.nur noch in der Liste. Und ich muss mühselig alle devices neu anlernen. Eine Kopie der device.db kann ich auch nicht machen da dann die Geräte zwar in der Liste auftauchen aber nicht mehr angenommen werden und sich nicht schalten lassen.

Was kann ich tun oder wie kann ich das Löschen der device.db verhindern?

**Comment by Sineos** [comment]
Gleiches Thema? https://github.com/hobbyquaker/node-red-contrib-zigbee/issues/74

**Comment by Matten-Matten** [comment]
@Sineos  vermutlich, bin mir aber nicht ganz sicher...

**Comment by Sineos** [comment]
Müsstes du eigentlich an deinem Flow erkennen. Wenn ich das Thema richtig verstanden habe, tritt der Effekt auf, wenn Zigbee-Geräte angesprochen werden, bevor die Zigbee-Nodes vollständig gestartet sind. 

Könnte man als Workaround einen kleinen Delay bei Flow-Start basteln.

**Comment by Matten-Matten** [comment]
OK muss ich schauen wo vor ich das baue....
Vermutlich vor das zigbee comand node?

**Comment by Sineos** [comment]
https://flows.nodered.org/node/node-red-contrib-simple-gate

Damit und einer Inject-Node + Trigger Node: Inject bei Start --> Trigger 10 sek und dann Simple Gate auf Open. 
Simple-Gate würde damit die Command Node "schützen" und ihr 10 Sekunden zum starten geben.

**Comment by Matten-Matten** [comment]
ok ich hab das jetzt selbst gebaut indem ich beim Start eine Datei mit false beschreibe und nach 20s wieder auf true setze. Und diese datei dann vor dem Device Node setze mit einer abfrage der Datei ( wenn diese auf true dann den datenstrom weiterfließen lassen sonst nicht). Ich denke das ist im prinzip das selbe. Mal schauen ob das was bringt die nächsten Tage.
@Sineos  Trotzdem vielen dank !

Gruß
Matten Matten
