### ISSUE TITLE
Renaming a device causes network disconnect

### ISSUE THREAD

**Issue by Sineos** [hobbyquaker/node-red-contrib-zigbee#77]
If I rename a device in the herdsman settings, the device is disconnected from the network and needs to be re-paired.

Is this by design or a bug?

**Comment by hobbyquaker** [comment]
I'm unable to reproduce this. To investigate further pls show logs on level debug

**Comment by Sineos** [comment]
Had two instances with this happening. Currently with RM 5.2.4 I cannot reproduce as well.
