### ISSUE TITLE
Error while opening serialport

### ISSUE THREAD

**Issue by schlaps2000** [hobbyquaker/node-red-contrib-zigbee#80]
Hallo

Seit dem Update von Redmatic 5.2.1 to 5.2.4 habe ich die Errormeldung "Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'" bzw. "herdsman not connected" in der Debugkonsole von Node-Red.

Unter der Version 5.2.1 lief alles sehr gut.
Selbst ein komplett neues Aufsetzen  von Raspberrymatic/Redmatic hat nur kurz abhilfe geschaffen.

Gibt es da irgendwie eine Lösung?

Raspberrymatic Version:3.47.22.20191130
Redmatic: 5.2.5
node-red-contrib-zigbee 1.6.4
CC2531:
version: "2.6.3",
revision: 20190619,
type: "zStack12"

Danke für eure Hilfe

**Comment by hobbyquaker** [comment]
Hast Du CUxD im Einsatz? Falls ja - der könnte dem Herdsman den seriellen Port "wegschnappen", siehe https://github.com/hobbyquaker/node-red-contrib-zigbee/issues/21#issuecomment-488761847

**Comment by schlaps2000** [comment]
Nein, CuxD ist nicht im einsatz.
Redmatic ist das einzige Addon.

**Comment by Sineos** [comment]
Aus den zusätzlichen packages irgendwelche installiert (serialport, comfoair etc.)?

**Comment by schlaps2000** [comment]
Nein, nur Redmatic-Homekit.
Das hatte ja alles bis zum update auf 5.2.4 alls super funktioniert

**Comment by Sineos** [comment]
Wenn du dich per SSH auf der Konsole anmeldest:

`ls -l /dev/serial/by-id`

Was kommt dabei raus?

Und:

`ls -l /proc/[0-9]*/fd/* | grep ttyACM0`

Sollte in etwa so was liefern:

```
ls: /proc/4188/fd/10: No such file or directory
ls: /proc/4188/fd/3: No such file or directory
ls: /proc/4188/fd/4: No such file or directory
lrwx------    1 root     root            64 Dec 16 19:02 /proc/27668/fd/25 -> /dev/ttyACM0
```

Dann in der letzten Zeile nimmst du die Zahl nach `/proc/` und dann:

`lsof | grep 27668`

Wobei du die 27668 durch deine Zahl ersetzt.

**Comment by schlaps2000** [comment]
Hallo Sineos,

danke für Deine Mühe.
Folgendes wirft die Konsole bei der Eingabe von `ls -l /dev/serial/by-id` aus:

`total 0
lrwxrwxrwx    1 root     root            13 Jan  1  1970 usb-Texas_Instruments_T                     I_CC2531_USB_CDC___0X00124B0011EE01EC-if00 -> ../../ttyACM0`

Bei `ls -l /proc/[0-9]*/fd/* | grep ttyACM0` bekommen ich folgendes:

`ls: /proc/3134/fd/10: No such file or directory
ls: /proc/3134/fd/3: No such file or directory
ls: /proc/3134/fd/4: No such file or directory
lrwx------    1 root     root            64 Dec 17 11:51 /proc/1035/fd/100 -> /d                     ev/ttyACM0
`
Bei ` lsof | grep 1035` kommt dann:

`1035    /usr/local/addons/redmatic/bin/node     /dev/null
1035    /usr/local/addons/redmatic/bin/node     pipe:[9866]
1035    /usr/local/addons/redmatic/bin/node     pipe:[9866]
1035    /usr/local/addons/redmatic/bin/node     anon_inode:[eventpoll]
1035    /usr/local/addons/redmatic/bin/node     pipe:[11501]
1035    /usr/local/addons/redmatic/bin/node     pipe:[11501]
1035    /usr/local/addons/redmatic/bin/node     pipe:[11502]
1035    /usr/local/addons/redmatic/bin/node     pipe:[11502]
1035    /usr/local/addons/redmatic/bin/node     anon_inode:[eventfd]
1035    /usr/local/addons/redmatic/bin/node     anon_inode:[eventpoll]
1035    /usr/local/addons/redmatic/bin/node     pipe:[11504]
1035    /usr/local/addons/redmatic/bin/node     pipe:[11504]
1035    /usr/local/addons/redmatic/bin/node     anon_inode:[eventfd]
1035    /usr/local/addons/redmatic/bin/node     anon_inode:[eventpoll]
1035    /usr/local/addons/redmatic/bin/node     pipe:[7836]
1035    /usr/local/addons/redmatic/bin/node     pipe:[7836]
1035    /usr/local/addons/redmatic/bin/node     anon_inode:[eventfd]
1035    /usr/local/addons/redmatic/bin/node     /dev/null
1035    /usr/local/addons/redmatic/bin/node     socket:[8075]
1035    /usr/local/addons/redmatic/bin/node     socket:[10980]
1035    /usr/local/addons/redmatic/bin/node     socket:[39440]
1035    /usr/local/addons/redmatic/bin/node     socket:[10985]
1035    /usr/local/addons/redmatic/bin/node     socket:[10986]
1035    /usr/local/addons/redmatic/bin/node     socket:[10987]
1035    /usr/local/addons/redmatic/bin/node     socket:[10988]
1035    /usr/local/addons/redmatic/bin/node     socket:[10991]
1035    /usr/local/addons/redmatic/bin/node     socket:[10994]
1035    /usr/local/addons/redmatic/bin/node     socket:[1198172]
1035    /usr/local/addons/redmatic/bin/node     socket:[73184]
1035    /usr/local/addons/redmatic/bin/node     socket:[1198173]
1035    /usr/local/addons/redmatic/bin/node     socket:[1198171]
1035    /usr/local/addons/redmatic/bin/node     socket:[11016]
1035    /usr/local/addons/redmatic/bin/node     socket:[11017]
1035    /usr/local/addons/redmatic/bin/node     socket:[11019]
1035    /usr/local/addons/redmatic/bin/node     socket:[11020]
1035    /usr/local/addons/redmatic/bin/node     socket:[12150]
1035    /usr/local/addons/redmatic/bin/node     socket:[12151]
1035    /usr/local/addons/redmatic/bin/node     socket:[12154]
1035    /usr/local/addons/redmatic/bin/node     socket:[12155]
1035    /usr/local/addons/redmatic/bin/node     socket:[10216]
1035    /usr/local/addons/redmatic/bin/node     socket:[10217]
1035    /usr/local/addons/redmatic/bin/node     socket:[1045396]
1035    /usr/local/addons/redmatic/bin/node     socket:[11033]
1035    /usr/local/addons/redmatic/bin/node     socket:[1045397]
1035    /usr/local/addons/redmatic/bin/node     socket:[790219]
1035    /usr/local/addons/redmatic/bin/node     socket:[10223]
1035    /usr/local/addons/redmatic/bin/node     socket:[10224]
1035    /usr/local/addons/redmatic/bin/node     socket:[790220]
1035    /usr/local/addons/redmatic/bin/node     socket:[790223]
1035    /usr/local/addons/redmatic/bin/node     socket:[11028]
1035    /usr/local/addons/redmatic/bin/node     socket:[790224]
1035    /usr/local/addons/redmatic/bin/node     socket:[790225]
1035    /usr/local/addons/redmatic/bin/node     socket:[11031]
1035    /usr/local/addons/redmatic/bin/node     socket:[790228]
1035    /usr/local/addons/redmatic/bin/node     socket:[1125323]
1035    /usr/local/addons/redmatic/bin/node     socket:[11039]
1035    /usr/local/addons/redmatic/bin/node     socket:[1125324]
1035    /usr/local/addons/redmatic/bin/node     socket:[790230]
1035    /usr/local/addons/redmatic/bin/node     socket:[790231]
1035    /usr/local/addons/redmatic/bin/node     socket:[1045400]
1035    /usr/local/addons/redmatic/bin/node     socket:[1045401]
1035    /usr/local/addons/redmatic/bin/node     socket:[11151]
1035    /usr/local/addons/redmatic/bin/node     socket:[52219]
1035    /usr/local/addons/redmatic/bin/node     socket:[58157]
1035    /usr/local/addons/redmatic/bin/node     socket:[8077]
1035    /usr/local/addons/redmatic/bin/node     socket:[11152]
1035    /usr/local/addons/redmatic/bin/node     socket:[12497]
1035    /usr/local/addons/redmatic/bin/node     socket:[11156]
1035    /usr/local/addons/redmatic/bin/node     socket:[11157]
1035    /usr/local/addons/redmatic/bin/node     socket:[11159]
1035    /usr/local/addons/redmatic/bin/node     socket:[11160]
1035    /usr/local/addons/redmatic/bin/node     socket:[12498]
1035    /usr/local/addons/redmatic/bin/node     socket:[1176332]
1035    /usr/local/addons/redmatic/bin/node     socket:[1176333]
1035    /usr/local/addons/redmatic/bin/node     socket:[1176336]
1035    /usr/local/addons/redmatic/bin/node     socket:[12502]
1035    /usr/local/addons/redmatic/bin/node     socket:[12504]
1035    /usr/local/addons/redmatic/bin/node     socket:[1176337]
1035    /usr/local/addons/redmatic/bin/node     socket:[1205554]
1035    /usr/local/addons/redmatic/bin/node     socket:[1205555]
1035    /usr/local/addons/redmatic/bin/node     socket:[1176343]
1035    /usr/local/addons/redmatic/bin/node     socket:[1176344]
1035    /usr/local/addons/redmatic/bin/node     socket:[1047083]
1035    /usr/local/addons/redmatic/bin/node     socket:[640095]
1035    /usr/local/addons/redmatic/bin/node     socket:[1047084]
1035    /usr/local/addons/redmatic/bin/node     socket:[1047086]
1035    /usr/local/addons/redmatic/bin/node     socket:[1047087]
1035    /usr/local/addons/redmatic/bin/node     socket:[1047089]
1035    /usr/local/addons/redmatic/bin/node     socket:[1047090]
1035    /usr/local/addons/redmatic/bin/node     socket:[1123204]
1035    /usr/local/addons/redmatic/bin/node     socket:[1202390]
1035    /usr/local/addons/redmatic/bin/node     socket:[1123203]
1035    /usr/local/addons/redmatic/bin/node     socket:[641760]
1035    /usr/local/addons/redmatic/bin/node     socket:[1195973]
1035    /usr/local/addons/redmatic/bin/node     socket:[1125327]
1035    /usr/local/addons/redmatic/bin/node     socket:[1200332]
1035    /usr/local/addons/redmatic/bin/node     socket:[1200291]
1035    /usr/local/addons/redmatic/bin/node     socket:[640097]
1035    /usr/local/addons/redmatic/bin/node     /dev/ttyACM0
1035    /usr/local/addons/redmatic/bin/node     socket:[641761]
1035    /usr/local/addons/redmatic/bin/node     socket:[1125328]
1035    /usr/local/addons/redmatic/bin/node     socket:[1125330]
1035    /usr/local/addons/redmatic/bin/node     socket:[1123210]
1035    /usr/local/addons/redmatic/bin/node     socket:[1125331]
1035    /usr/local/addons/redmatic/bin/node     socket:[1125334]
1035    /usr/local/addons/redmatic/bin/node     socket:[1123214]
1035    /usr/local/addons/redmatic/bin/node     socket:[1125335]
1035    /usr/local/addons/redmatic/bin/node     socket:[1047092]
1035    /usr/local/addons/redmatic/bin/node     socket:[1205557]
1035    /usr/local/addons/redmatic/bin/node     socket:[39442]
1035    /usr/local/addons/redmatic/bin/node     socket:[1176348]
1035    /usr/local/addons/redmatic/bin/node     socket:[52220]
1035    /usr/local/addons/redmatic/bin/node     socket:[1205558]
1035    /usr/local/addons/redmatic/bin/node     socket:[1176351]
1035    /usr/local/addons/redmatic/bin/node     socket:[1202384]
1035    /usr/local/addons/redmatic/bin/node     socket:[58158]
1035    /usr/local/addons/redmatic/bin/node     socket:[1047093]
1035    /usr/local/addons/redmatic/bin/node     socket:[73186]
1035    /usr/local/addons/redmatic/bin/node     socket:[1195974]
1035    /usr/local/addons/redmatic/bin/node     socket:[1202385]
1035    /usr/local/addons/redmatic/bin/node     socket:[1202391]
1035    /usr/local/addons/redmatic/bin/node     socket:[1201928]
1035    /usr/local/addons/redmatic/bin/node     socket:[1201929]
1035    /usr/local/addons/redmatic/bin/node     socket:[1201931]
1035    /usr/local/addons/redmatic/bin/node     socket:[1201932]
1035    /usr/local/addons/redmatic/bin/node     socket:[1207955]
1035    /usr/local/addons/redmatic/bin/node     socket:[1209987]
1035    /usr/local/addons/redmatic/bin/node     socket:[1209988]
1035    /usr/local/addons/redmatic/bin/node     socket:[1209991]
1035    /usr/local/addons/redmatic/bin/node     socket:[1209992]
1035    /usr/local/addons/redmatic/bin/node     socket:[1186340]
1035    /usr/local/addons/redmatic/bin/node     socket:[1186341]
1035    /usr/local/addons/redmatic/bin/node     socket:[1186344]
1035    /usr/local/addons/redmatic/bin/node     socket:[1186343]
1035    /usr/local/addons/redmatic/bin/node     socket:[1186346]
1035    /usr/local/addons/redmatic/bin/node     socket:[1186347]
1035    /usr/local/addons/redmatic/bin/node     socket:[1186348]
1035    /usr/local/addons/redmatic/bin/node     socket:[1186350]`

Momentan funktioniert der hersdman ohne Fehlermeldung.
Habe auch 7 Divices gepairt bekommen. 
Leider hat es bei den letzten Versuchen davor nicht lange gehalten, bis dann die oben genannten Fehlermeldungen kamen.

**Comment by Sineos** [comment]
Was die Befehle zeigen, ist dass die device ttyACM0 nur von Node-Red in Beschlag ist und von keinem anderen Prozess. 

Wenn der Fehler nochmal auftritt mach bitte das selbe nochmal, dann können wir schauen ob eine nicht NR Prozess sich die device schnappt (was eigentlich nicht passieren dürfte, außer bei CUXd)

**Comment by schlaps2000** [comment]
Hallo @Sineos 
Nun ist es endlich wieder soweit :(
Nach dem ich einen der letzten Sensoren gepairt hatte, ist alles abgeschmiert.
Erst diese Fehlermeldung:"Cannot read property '1' of undefined"
Danach gleich: "Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port'"
 Zur Ausgabe der Konsole:
Befehl `ls -l /dev/serial/by-id` gibt aus:
`total 0
lrwxrwxrwx    1 root     root            13             Jan  1  1970 usb-Texas_Instruments_TI_CC25            31_USB_CDC___0X00124B0011EE01EC-if00 -> ../            ../ttyACM0
`

Befehl `ls -l /proc/[0-9]*/fd/* | grep ttyACM0` gibt aus:
`ls: /proc/27937/fd/10: No such file or directory
ls: /proc/27937/fd/3: No such file or directory
ls: /proc/27937/fd/4: No such file or directory
lrwx------    1 root     root            64 Dec 18 12:05 /proc/15596/fd/92 -> /dev/ttyACM0`

Befehl `lsof | grep 15596` gibt aus:
`15596   /usr/local/addons/redmatic/bin/node     /dev/nu                                                                                                                                              ll
15596   /usr/local/addons/redmatic/bin/node     pipe:[2                                                                                                                                              471619]
15596   /usr/local/addons/redmatic/bin/node     pipe:[2                                                                                                                                              471619]
15596   /usr/local/addons/redmatic/bin/node     anon_in                                                                                                                                              ode:[eventpoll]
15596   /usr/local/addons/redmatic/bin/node     pipe:[2                                                                                                                                              473314]
15596   /usr/local/addons/redmatic/bin/node     pipe:[2                                                                                                                                              473314]
15596   /usr/local/addons/redmatic/bin/node     pipe:[2                                                                                                                                              473315]
15596   /usr/local/addons/redmatic/bin/node     pipe:[2                                                                                                                                              473315]
15596   /usr/local/addons/redmatic/bin/node     anon_in                                                                                                                                              ode:[eventfd]
15596   /usr/local/addons/redmatic/bin/node     anon_in                                                                                                                                              ode:[eventpoll]
15596   /usr/local/addons/redmatic/bin/node     pipe:[2                                                                                                                                              473316]
15596   /usr/local/addons/redmatic/bin/node     pipe:[2                                                                                                                                              473316]
15596   /usr/local/addons/redmatic/bin/node     anon_in                                                                                                                                              ode:[eventfd]
15596   /usr/local/addons/redmatic/bin/node     anon_in                                                                                                                                              ode:[eventpoll]
15596   /usr/local/addons/redmatic/bin/node     pipe:[2                                                                                                                                              470860]
15596   /usr/local/addons/redmatic/bin/node     pipe:[2                                                                                                                                              470860]
15596   /usr/local/addons/redmatic/bin/node     anon_in                                                                                                                                              ode:[eventfd]
15596   /usr/local/addons/redmatic/bin/node     /dev/nu                                                                                                                                              ll
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2471724]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2471672]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2562888]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2471679]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2471680]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2471681]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2471682]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2471685]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2471688]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2552350]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2484992]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2552351]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2552471]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2471767]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2523937]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2526492]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2471725]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2472582]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2472583]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2471729]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2471730]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2501173]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2501174]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2471734]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2471735]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2559045]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2499180]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2552130]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2552131]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2471743]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2471742]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2501177]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2501178]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2471748]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2471749]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2499181]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2499183]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2552134]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2552133]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2471756]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2548199]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2471758]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2499184]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2552136]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2471761]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2548200]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2471763]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2499185]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2552137]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2548202]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2471771]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2499189]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2552138]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2471777]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2548203]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2471781]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2499187]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2552140]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2551136]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2551137]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2551139]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2499190]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2551140]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2523387]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2523388]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2523390]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2472593]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2523391]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2472594]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2550416]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2558477]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2472598]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2559021]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2472600]
15596   /usr/local/addons/redmatic/bin/node     /dev/tt                                                                                                                                              yACM0
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2472604]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2472605]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2472607]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2532715]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2535652]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2472611]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2484993]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2523393]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2523394]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2523396]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2552144]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2552145]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2523397]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2552147]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2559039]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2523939]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2552148]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2550418]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2526493]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2559040]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2532717]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2559046]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2535653]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2560595]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2560596]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2560598]
15596   /usr/local/addons/redmatic/bin/node     socket:                                                                                                                                              [2560599]
`

![grafik](https://user-images.githubusercontent.com/58888898/71081399-68c4f680-218f-11ea-83dc-c64e930b6d90.png)

Das komische ist, das sich die diesesmal die Steckdosen und Lampen über Homekit bedinen lassen.
Der Satus der Fenstersensoren wir aber nicht angezeigt bzw aktuallisiert.
Die Fehlermeldungen kamen meisten wenn ich eine der Fenstersensoren gepairt hatte ( Aqara:LUMI
lumi.sensor_magnet.aq2)

**Comment by schlaps2000** [comment]
Was mir eben noch aufgefallen ist:
In der Datei dev.db wurde mir ein unbekanntes Device hinterlegt:
`{"id":15,"ieeeAddr":"0x00158d000346a9a6","nwkAddr":57028,"epList":[],"endpoints":{},"interviewCompleted":false,"meta":{}}
{"id":16,"ieeeAddr":"0x00158d000346a9a6","nwkAddr":30730,"epList":[],"endpoints":{},"interviewCompleted":false,"meta":{"name":"undefined"}}`

Ist das korrekt so? Ein Device mit dieser ieeeAdresse habe ich nicht...
Es taucht auch nicht in der Devicelist im Herdsman auf.

**Comment by Sineos** [comment]
Ok, jetzt bin ich raus. Die tty device ist im System richtig angelegt und gehört NR, also von der Seite aus scheinbar alles richtig. Jetzt müssen die Profis ran ;-) 

Wenn ich jetzt sehr verzweifelt wäre würde ich noch folgendes probieren:
- Zigbee Stick neu flashen (gibt Berichte, dass die Firmware nen Schatten bekommen kann)
- dev.db und Backup löschen
- Neue panID vergeben
- Alle Geräte neu pairen
Das kann aber auch gut ein "Außer Spesen nix gewesen" sein.

@hobbyquaker 
Geht sowas `DEBUG=zigbee-herdsman:controller* npm start` in NR?

**Comment by hobbyquaker** [comment]
kann es sein dass du zwei herdsman config nodes hast? davon darf es nur einen geben.

**Comment by schlaps2000** [comment]
@hobbyquaker 
Es ist kein zweiter herdsman vorhanden, auch kein inaktiver.
@Sineos 
Ich hatte alles komplett neu aufgesetzt (Raspberrymatic, Redmatic).
Bei Redmatic ist auch nichts aus alten Backups gezogen, sondern neu erstellt.
- Der Stick ist neu geflashed.
- Die panID kann ich noch mal testen

Momentan läuft es aber sauber. Lasse jetzt ermal die Finger davon.

Danke für Eure Hilfe.

**Comment by 18akallfass87** [comment]
Hallo zusammen,

ich habe das selbe Problem und bekomme es nach wie vor nicht gelöst.

Wo komme ich überhaubt 

Kann ich den Befehl "ls -l /dev/serial/by-id"  nur über Linux eingeben oder gibt es da noch eine andere Möglichkeit?

Vielen Dank im Voraus!

Gruss, Andreas
